(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={ca:!0},ea={};try{ea.__proto__=da;ca=ea.ca;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.v=b.prototype}var ia="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ja(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var ka=ja(this);function la(a,b){if(b){var c=ka;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ia(c,a,{configurable:!0,writable:!0,value:b})}}
var ma=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();la("Reflect.construct",function(){return ma});
la("Object.setPrototypeOf",function(a){return a||fa});var l=this||self;function na(){}
function oa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function m(a){return"array"==oa(a)}function pa(a){var b=oa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function n(a){return"function"==oa(a)}function q(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var qa="closure_uid_"+(1E9*Math.random()>>>0),ra=0;function sa(a,b,c){return a.call.apply(a.bind,arguments)}
function ta(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function r(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?r=sa:r=ta;return r.apply(null,arguments)}
function ua(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var va=Date.now||function(){return+new Date};function t(a,b){function c(){}c.prototype=b.prototype;a.v=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.sa=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var wa;var xa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ya=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},za=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d},Aa=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};function Ba(a,b){return 0<=xa(a,b)}
function Ca(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Da=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ea(a,b){if(b)a=a.replace(Fa,"&amp;").replace(Ga,"&lt;").replace(Ha,"&gt;").replace(Ia,"&quot;").replace(Ja,"&#39;").replace(Ka,"&#0;");else{if(!La.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Fa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ga,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ha,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ia,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ja,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ka,"&#0;"))}return a}
var Fa=/&/g,Ga=/</g,Ha=/>/g,Ia=/"/g,Ja=/'/g,Ka=/\x00/g,La=/[\x00&<>"']/;function Ma(a,b){return a<b?-1:a>b?1:0};var u;a:{var Na=l.navigator;if(Na){var Oa=Na.userAgent;if(Oa){u=Oa;break a}}u=""};function Pa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Qa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}function Ra(){var a=v,b;for(b in a)return!1;return!0}var Sa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ta(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Sa.length;f++)c=Sa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function w(){this.b="";this.f=Ua;this.c=null}w.prototype.ha=!0;w.prototype.a=function(){return this.c};w.prototype.$=!0;w.prototype.Y=function(){return this.b.toString()};function Va(a){return a instanceof w&&a.constructor===w&&a.f===Ua?a.b:"type_error:SafeHtml"}function Wa(a){if(a instanceof w)return a;var b="object"==typeof a,c=null;b&&a.ha&&(c=a.a());a=Ea(b&&a.$?a.Y():String(a));return x(a,c)}
function Xa(a){function b(f){m(f)?ya(f,b):(f=Wa(f),e.push(Va(f).toString()),f=f.a(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=Wa(Ya),d=c.a(),e=[];ya(a,b);return x(e.join(Va(c).toString()),d)}function Za(a){return Xa(Array.prototype.slice.call(arguments))}var Ua={};function x(a,b){var c=new w;c.b=a;c.c=b;return c}x("<!DOCTYPE html>",0);var Ya=x("",0),$a=x("<br>",0);var ab=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=Va(Ya);return!b.parentElement});function bb(a,b){if(ab())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=Va(b)};function cb(a){return a=Ea(a,void 0)};function db(a){db[" "](a);return a}db[" "]=na;function eb(a,b){var c=fb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var gb=-1!=u.indexOf("Opera"),y=-1!=u.indexOf("Trident")||-1!=u.indexOf("MSIE"),z=-1!=u.indexOf("Edge"),A=-1!=u.indexOf("Gecko")&&!(-1!=u.toLowerCase().indexOf("webkit")&&-1==u.indexOf("Edge"))&&!(-1!=u.indexOf("Trident")||-1!=u.indexOf("MSIE"))&&-1==u.indexOf("Edge"),B=-1!=u.toLowerCase().indexOf("webkit")&&-1==u.indexOf("Edge"),C=-1!=u.indexOf("Macintosh");function hb(){var a=l.document;return a?a.documentMode:void 0}var ib;
a:{var jb="",kb=function(){var a=u;if(A)return/rv:([^\);]+)(\)|;)/.exec(a);if(z)return/Edge\/([\d\.]+)/.exec(a);if(y)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(B)return/WebKit\/(\S+)/.exec(a);if(gb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();kb&&(jb=kb?kb[1]:"");if(y){var lb=hb();if(null!=lb&&lb>parseFloat(jb)){ib=String(lb);break a}}ib=jb}var mb=ib,fb={};
function D(a){return eb(a,function(){for(var b=0,c=Da(String(mb)).split("."),d=Da(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=Ma(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||Ma(0==h[2].length,0==k[2].length)||Ma(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var E;E=l.document&&y?hb():void 0;var nb=!y||9<=Number(E),ob=!y||9<=Number(E),pb=y&&!D("9"),qb=function(){if(!l.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{l.addEventListener("test",na,b),l.removeEventListener("test",na,b)}catch(c){}return a}();function F(){this.D=this.D;this.m=this.m}g=F.prototype;g.D=!1;g.ia=function(){return this.D};g.Ja=F.prototype.ia;g.R=function(){this.D||(this.D=!0,this.i())};g.ec=function(a){a=ua(rb,a);this.D?a():(this.m||(this.m=[]),this.m.push(a))};g.i=function(){if(this.m)for(;this.m.length;)this.m.shift()()};function rb(a){a&&"function"==typeof a.R&&a.R()};function G(a,b){this.type=a;this.c=this.target=b;this.defaultPrevented=this.f=!1}G.prototype.stopPropagation=function(){this.f=!0};G.prototype.preventDefault=function(){this.defaultPrevented=!0};function H(a,b){G.call(this,a?a.type:"");this.relatedTarget=this.c=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.o=this.m=0;this.key="";this.g=this.a=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.u=null;this.G=!1;this.pointerId=0;this.pointerType="";this.b=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.c=b;if(b=a.relatedTarget){if(A){a:{try{db(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.m=B||void 0!==a.offsetX?a.offsetX:a.layerX,this.o=B||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.a=a.keyCode||0;this.key=a.key||"";this.g=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.G=C?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:sb[a.pointerType]||"";this.u=a.state;this.b=a;a.defaultPrevented&&this.preventDefault()}}t(H,G);var tb=[1,4,2],sb={2:"touch",3:"pen",4:"mouse"};
H.prototype.N=function(){return(nb?0==this.b.button:"click"==this.type?!0:!!(this.b.button&tb[0]))&&!(B&&C&&this.ctrlKey)};H.prototype.stopPropagation=function(){H.v.stopPropagation.call(this);this.b.stopPropagation?this.b.stopPropagation():this.b.cancelBubble=!0};H.prototype.preventDefault=function(){H.v.preventDefault.call(this);var a=this.b;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,pb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var ub="closure_listenable_"+(1E6*Math.random()|0);function I(a){return!(!a||!a[ub])}var vb=0;function wb(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.K=e;this.key=++vb;this.H=this.J=!1}function xb(a){a.H=!0;a.listener=null;a.a=null;a.src=null;a.K=null};function J(a){this.src=a;this.a={};this.b=0}J.prototype.c=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};J.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=yb(a,b,d,e);-1<h?(b=a[h],c||(b.J=!1)):(b=new wb(b,this.src,f,!!d,e),b.J=c,a.push(b));return b};
function zb(a,b){var c=b.type;if(!(c in a.a))return!1;var d=a.a[c],e=xa(d,b),f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);f&&(xb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return f}function Ab(a){var b=0,c;for(c in a.a){for(var d=a.a[c],e=0;e<d.length;e++)++b,xb(d[e]);delete a.a[c];a.b--}}function Bb(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=yb(a,c,d,e));return-1<b?a[b]:null}
function Cb(a,b,c){var d=void 0!==b,e=d?b.toString():"",f=void 0!==c;return Qa(a.a,function(h){for(var k=0;k<h.length;++k)if(!(d&&h[k].type!=e||f&&h[k].capture!=c))return!0;return!1})}function yb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.H&&f.listener==b&&f.capture==!!c&&f.K==d)return e}return-1};var Db="closure_lm_"+(1E6*Math.random()|0),Eb={},Fb=0;function K(a,b,c,d,e){if(d&&d.once)return Gb(a,b,c,d,e);if(m(b)){for(var f=0;f<b.length;f++)K(a,b[f],c,d,e);return null}c=Hb(c);return I(a)?a.B(b,c,q(d)?!!d.capture:!!d,e):Ib(a,b,c,!1,d,e)}
function Ib(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=q(e)?!!e.capture:!!e,k=L(a);k||(a[Db]=k=new J(a));c=k.add(b,c,d,h,f);if(c.a)return c;d=Jb();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)qb||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Kb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Fb++;return c}
function Jb(){var a=Lb,b=ob?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Gb(a,b,c,d,e){if(m(b)){for(var f=0;f<b.length;f++)Gb(a,b[f],c,d,e);return null}c=Hb(c);return I(a)?a.j.add(String(b),c,!0,q(d)?!!d.capture:!!d,e):Ib(a,b,c,!0,d,e)}function Mb(a,b,c,d,e){if(m(b))for(var f=0;f<b.length;f++)Mb(a,b[f],c,d,e);else d=q(d)?!!d.capture:!!d,c=Hb(c),I(a)?a.O(b,c,d,e):a&&(a=L(a))&&(b=Bb(a,b,c,d,e))&&M(b)}
function M(a){if("number"===typeof a||!a||a.H)return!1;var b=a.src;if(I(b))return zb(b.j,a);var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Kb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Fb--;(c=L(b))?(zb(c,a),0==c.b&&(c.src=null,b[Db]=null)):xb(a);return!0}function Nb(a){if(a)if(I(a))a.j&&Ab(a.j);else if(a=L(a)){var b=0,c;for(c in a.a)for(var d=a.a[c].concat(),e=0;e<d.length;++e)M(d[e])&&++b}}
function Kb(a){return a in Eb?Eb[a]:Eb[a]="on"+a}function Ob(a,b,c,d){var e=!0;if(a=L(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.H&&(f=Pb(f,d),e=e&&!1!==f)}return e}function Pb(a,b){var c=a.listener,d=a.K||a.src;a.J&&M(a);return c.call(d,b)}
function Lb(a,b){if(a.H)return!0;if(!ob){if(!b)a:{b=["window","event"];for(var c=l,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new H(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.c;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.f&&0<=e;e--){b.c=d[e];var f=Ob(d[e],a,!0,b);c=c&&f}for(e=0;!b.f&&e<d.length;e++)b.c=d[e],f=Ob(d[e],a,!1,b),c=
c&&f}return c}return Pb(a,new H(b,this))}function L(a){a=a[Db];return a instanceof J?a:null}var Qb="__closure_events_fn_"+(1E9*Math.random()>>>0);function Hb(a){if(n(a))return a;a[Qb]||(a[Qb]=function(b){return a.handleEvent(b)});return a[Qb]};var Rb=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Rb&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function N(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ha(N,HTMLElement);N.prototype.f=function(){console.warn(this.tagName,"has not implemented update")};N.prototype.b=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
N.prototype.c=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};var Sb;var Tb=!y||9<=Number(E),Ub=!A&&!y||y&&9<=Number(E)||A&&D("1.9.1"),Vb=y&&!D("9"),Wb=y||gb||B;function O(a,b){this.a=void 0!==a?a:0;this.b=void 0!==b?b:0}g=O.prototype;g.Gb=function(){return new O(this.a,this.b)};g.xa=function(a){return a instanceof O&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};g.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};g.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};g.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
g.Ib=function(a,b){a instanceof O?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),"number"===typeof b&&(this.b+=b));return this};g.Hb=function(a,b){this.a*=a;this.b*="number"===typeof b?b:a;return this};g.hc=function(a,b){a=a*Math.PI/180;b=b||new O(0,0);var c=this.a,d=this.b,e=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*e-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*e+b.b};function Xb(a,b){this.width=a;this.height=b}g=Xb.prototype;g.Jb=function(){return new Xb(this.width,this.height)};g.Xa=function(){return Math.max(this.width,this.height)};g.kb=function(){return Math.min(this.width,this.height)};g.dc=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.Rb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.Ba=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Yb(a,b){a.width*=b;a.height*=b;return a}g.jc=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Yb(this,a)};
g.kc=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Yb(this,a)};function Zb(a){return a?new P(Q(a)):wa||(wa=new P)}function $b(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=ac(document,"*",a,b);return d||null}
function bc(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&Ba(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a}
function ac(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):bc(a,b,c,d)[0]||null}function cc(a,b){Pa(b,function(c,d){c&&"object"==typeof c&&c.$&&(c=c.Y());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:dc.hasOwnProperty(d)?a.setAttribute(dc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var dc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function ec(a){a=a.document;a=fc(a)?a.documentElement:a.body;return new Xb(a.clientWidth,a.clientHeight)}function gc(a){return a.scrollingElement?a.scrollingElement:!B&&fc(a)?a.documentElement:a.body||a.documentElement}
function hc(a){return a.parentWindow||a.defaultView}function ic(a,b,c,d){function e(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];pa(f)&&!jc(f)?ya(kc(f)?Ca(f):f,e):e(f)}}function R(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function fc(a){return"CSS1Compat"==a.compatMode}function lc(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function mc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function nc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function jc(a){return q(a)&&0<a.nodeType}function oc(a){return q(a)&&1==a.nodeType}function qc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function rc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return sc(b,a)}function sc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function Q(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function tc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else lc(a),a.appendChild(Q(a).createTextNode(String(b)))}function uc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||uc(a,b,c,d))return!0;a=a.nextSibling}return!1}var vc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},wc={IMG:" ",BR:"\n"};
function xc(a){return yc(a)&&zc(a)}function yc(a){return y&&!D("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function zc(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function Ac(a){if(Vb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Bc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Vb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function Bc(a,b,c){if(!(a.nodeName in vc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in wc)b.push(wc[a.nodeName]);else for(a=a.firstChild;a;)Bc(a,b,c),a=a.nextSibling}function kc(a){if(a&&"number"==typeof a.length){if(q(a))return"function"==typeof a.item||"string"==typeof a.item;if(n(a))return"function"==typeof a.item}return!1}
function Cc(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return Dc(a,function(f){return(!e||f.nodeName==e)&&(!c||"string"===typeof f.className&&Ba(f.className.split(/\s+/),c))},!0,d)}function Dc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function P(a){this.a=a||l.document||document}g=P.prototype;g.Oa=Zb;g.lc=function(a){this.a=a};g.Ka=function(){return this.a};
g.I=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.ib=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.oa=P.prototype.I;g.wb=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.ea=function(a,b,c){return bc(this.a,a,b,c)};g.Ra=function(a,b,c){return ac(this.a,a,b,c)};g.Sa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):bc(document,"*",a,b)};g.Qa=function(a,b){return $b(a,b||this.a)};
g.jb=function(a,b){return $b(a,b||this.a)};g.pa=P.prototype.ea;g.rc=cc;g.mb=function(a){return ec(a||hc(this.a)||window)};g.La=function(){var a=hc(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=ec(a).height,fc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.X=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!Tb&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',cb(h.name),'"');if(h.type){f.push(' type="',cb(h.type),'"');var k={};Ta(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=R(d,f);h&&("string"===typeof h?f.className=h:m(h)?f.className=h.join(" "):cc(f,h));2<e.length&&ic(d,f,e,2);return f};g.qa=P.prototype.X;g.ub=function(a){return R(this.a,a)};g.vb=function(a){return this.a.createTextNode(String(a))};
g.ua=function(a,b,c){var d=this.a;c=!!c;for(var e=R(d,"TABLE"),f=e.appendChild(R(d,"TBODY")),h=0;h<a;h++){for(var k=R(d,"TR"),p=0;p<b;p++){var pc=R(d,"TD");c&&tc(pc,"\u00a0");k.appendChild(pc)}f.appendChild(k)}return e};g.ic=function(a){var b=this.a;var c=R(b,"DIV");y?(a=Za($a,a),bb(c,a),c.removeChild(c.firstChild)):bb(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.Pb=function(){return fc(this.a)};
g.Na=function(){return gc(this.a)};g.Ma=function(){var a=this.a,b=gc(a);a=hc(a);return y&&D("10")&&a.pageYOffset!=b.scrollTop?new O(b.scrollLeft,b.scrollTop):new O(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.Da=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.rb=function(a,b){a.appendChild(b)};g.qb=function(a,b){ic(Q(a),a,arguments,1)};g.sb=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.gc=lc;g.Nb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.Mb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.Lb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.xb=mc;g.yb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.Ca=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return mc(a)}};
g.Ia=function(a){return Ub&&void 0!=a.children?a.children:za(a.childNodes,function(b){return 1==b.nodeType})};g.Ta=function(a){return void 0!==a.firstElementChild?a.firstElementChild:nc(a.firstChild,!0)};g.Wa=function(a){return void 0!==a.lastElementChild?a.lastElementChild:nc(a.lastChild,!1)};g.Ya=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:nc(a.nextSibling,!0)};g.gb=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:nc(a.previousSibling,!1)};
g.Za=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.hb=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.Wb=jc;g.Qb=oc;g.Zb=function(a){return q(a)&&a.window==a};g.fb=function(a){var b;if(Wb&&!(y&&D("9")&&!D("10")&&l.SVGElement&&a instanceof l.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return oc(b)?b:null};
g.tb=qc;
g.ta=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(y&&!(9<=Number(E))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?sc(a,b):!c&&qc(e,b)?-1*rc(a,b):!d&&qc(f,a)?rc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=Q(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(l.Range.START_TO_END,a)};g.ya=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.eb=Q;g.Ua=function(a){return a.contentDocument||a.contentWindow.document};
g.Va=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?hc(c):window}else d=null;b=d}return b}catch(e){}return null};g.tc=tc;g.cb=function(a){if("outerHTML"in a)return a.outerHTML;var b=R(Q(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.za=function(a,b){var c=[];return uc(a,b,c,!0)?c[0]:void 0};g.Aa=function(a,b){var c=[];uc(a,b,c,!1);return c};g.Tb=xc;g.mc=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.Sb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!yc(a)||zc(a)):xc(a))&&y){var c;!n(a.getBoundingClientRect)||y&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.lb=Ac;g.ab=function(a){return Ac(a).length};
g.bb=function(a,b){b=b||Q(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(Ac(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.$a=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in vc))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in wc)d+=wc[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);q(c)&&(c.fc=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.Xb=kc;g.Ga=Cc;g.Fa=function(a,b,c){return Cc(a,null,b,c)};g.Ea=Dc;g.Ha=function(a){return a.getContext("2d")};function Ec(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")};function Fc(a){return"string"==typeof a.className?a.className:a.getAttribute&&a.getAttribute("class")||""}function Gc(a,b){"string"==typeof a.className?a.className=b:a.setAttribute&&a.setAttribute("class",b)}function Hc(a,b){return a.classList?a.classList.contains(b):Ba(a.classList?a.classList:Fc(a).match(/\S+/g)||[],b)}function S(a,b){if(a.classList)a.classList.add(b);else if(!Hc(a,b)){var c=Fc(a);Gc(a,c+(0<c.length?" "+b:b))}}
function Ic(a,b){a.classList?a.classList.remove(b):Hc(a,b)&&Gc(a,za(a.classList?a.classList:Fc(a).match(/\S+/g)||[],function(c){return c!=b}).join(" "))};function T(a){F.call(this);this.b=a;this.a={}}t(T,F);var Jc=[];g=T.prototype;g.B=function(a,b,c,d){return Kc(this,a,b,c,d)};g.ac=function(a,b,c,d,e){return Kc(this,a,b,c,d,e)};function Kc(a,b,c,d,e,f){m(c)||(c&&(Jc[0]=c.toString()),c=Jc);for(var h=0;h<c.length;h++){var k=K(b,c[h],d||a.handleEvent,e||!1,f||a.b||a);if(!k)break;a.a[k.key]=k}return a}g.Ab=function(a,b,c,d){return Lc(this,a,b,c,d)};g.$b=function(a,b,c,d,e){return Lc(this,a,b,c,d,e)};
function Lc(a,b,c,d,e,f){if(m(c))for(var h=0;h<c.length;h++)Lc(a,b,c[h],d,e,f);else{b=Gb(b,c,d||a.handleEvent,e,f||a.b||a);if(!b)return a;a.a[b.key]=b}return a}g.bc=function(a,b,c,d){b.B(a,c,d,this.b||this);return this};g.cc=function(a,b,c,d,e){b.B(a,c,d,e||this.b||this);return this};g.zb=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
g.O=function(a,b,c,d,e){if(m(b))for(var f=0;f<b.length;f++)this.O(a,b[f],c,d,e);else c=c||this.handleEvent,d=q(d)?!!d.capture:!!d,e=e||this.b||this,c=Hb(c),d=!!d,b=I(a)?Bb(a.j,String(b),c,d,e):a?(a=L(a))?Bb(a,b,c,d,e):null:null,b&&(M(b),delete this.a[b.key])};g.uc=function(a,b,c,d,e){b.O(a,c,d,e||this.b||this,this);return this};function Mc(a){Pa(a.a,function(b,c){this.a.hasOwnProperty(c)&&M(b)},a);a.a={}}g.i=function(){T.v.i.call(this);Mc(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function U(){F.call(this);this.j=new J(this);this.aa=this;this.G=null}t(U,F);U.prototype[ub]=!0;g=U.prototype;g.pc=function(a){this.G=a};g.Bb=function(a,b,c,d){K(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){Mb(this,a,b,c,d)};
function V(a,b){var c,d=a.G;if(d)for(c=[];d;d=d.G)c.push(d);a=a.aa;d=b.type||b;if("string"===typeof b)b=new G(b,a);else if(b instanceof G)b.target=b.target||a;else{var e=b;b=new G(d,a);Ta(b,e)}e=!0;if(c)for(var f=c.length-1;!b.f&&0<=f;f--){var h=b.c=c[f];e=Nc(h,d,!0,b)&&e}b.f||(h=b.c=a,e=Nc(h,d,!0,b)&&e,b.f||(e=Nc(h,d,!1,b)&&e));if(c)for(f=0;!b.f&&f<c.length;f++)h=b.c=c[f],e=Nc(h,d,!1,b)&&e}g.i=function(){U.v.i.call(this);this.j&&Ab(this.j);this.G=null};
g.B=function(a,b,c,d){return this.j.add(String(a),b,!1,c,d)};g.O=function(a,b,c,d){var e=this.j;a=String(a).toString();if(a in e.a){var f=e.a[a];b=yb(f,b,c,d);-1<b&&(xb(f[b]),Array.prototype.splice.call(f,b,1),0==f.length&&(delete e.a[a],e.b--))}};function Nc(a,b,c,d){b=a.j.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var h=b[f];if(h&&!h.H&&h.capture==c){var k=h.listener,p=h.K||h.src;h.J&&zb(a.j,h);e=!1!==k.call(p,d)&&e}}return e&&!d.defaultPrevented}
g.Cb=function(a,b){a=this.j.a[String(a).toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};g.Db=function(a,b){return Cb(this.j,void 0!==a?String(a):void 0,b)};g.sc=function(a){this.aa=a};g.ra=function(){};function Oc(a,b,c){F.call(this);this.a=a;this.f=b||0;this.b=c;this.c=r(this.Z,this)}t(Oc,F);g=Oc.prototype;g.w=0;g.i=function(){Oc.v.i.call(this);Pc(this);delete this.a;delete this.b};g.start=function(a){Pc(this);var b=this.c;a=void 0!==a?a:this.f;if(!n(b))if(b&&"function"==typeof b.handleEvent)b=r(b.handleEvent,b);else throw Error("Invalid listener argument");this.w=2147483647<Number(a)?-1:l.setTimeout(b,a||0)};g.pb=function(a){0!=this.w||this.start(a)};
function Pc(a){0!=a.w&&l.clearTimeout(a.w);a.w=0}g.ob=function(){0!=this.w&&(Pc(this),this.Z())};g.Z=function(){this.w=0;this.a&&this.a.call(this.b)};var v={},W=null;function Qc(a){a=a[qa]||(a[qa]=++ra);delete v[a];Ra()&&W&&Pc(W)}function Rc(){W||(W=new Oc(function(){Sc()},20));var a=W;0!=a.w||a.start()}function Sc(){var a=va();Pa(v,function(b){Tc(b,a)});Ra()||Rc()};function Uc(){U.call(this);this.a=0;this.endTime=this.b=null}t(Uc,U);Uc.prototype.l=function(a){V(this,a)};function Vc(a,b,c,d){Uc.call(this);if(!m(a)||!m(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.c=a;this.A=b;this.duration=c;this.g=d;this.coords=[];this.u=!1;this.progress=this.o=0;this.f=null}t(Vc,Uc);g=Vc.prototype;g.Pa=function(){return this.duration};g.wa=function(a){this.u=a};g.Yb=function(){return this.u};function Wc(a){Qc(a);a.a=0;Xc(a,a.progress);a.l("stop");a.l("end")}
g.Fb=function(){1==this.a&&(Qc(this),this.a=-1,this.l("pause"))};g.qc=function(a){this.progress=a;1==this.a&&(this.b=va()-this.duration*this.progress,this.endTime=this.b+this.duration)};g.i=function(){0==this.a||Wc(this);this.l("destroy");Vc.v.i.call(this)};g.va=function(){this.R()};
function Tc(a,b){b<a.b&&(a.endTime=b+a.endTime-a.b,a.b=b);a.progress=(b-a.b)/(a.endTime-a.b);1<a.progress&&(a.progress=1);a.o=1E3/(b-a.f);a.f=b;Xc(a,a.progress);1==a.progress?(a.a=0,Qc(a),a.l("finish"),a.l("end")):1==a.a&&a.l("animate")}function Xc(a,b){n(a.g)&&(b=a.g(b));a.coords=Array(a.c.length);for(var c=0;c<a.c.length;c++)a.coords[c]=(a.A[c]-a.c[c])*b+a.c[c]}g.l=function(a){V(this,new Yc(a,this))};
function Yc(a,b){G.call(this,a);this.coords=b.coords;this.o=b.coords[0];this.A=b.coords[1];this.u=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.g=b.o;this.m=b.a;this.a=b}t(Yc,G);Yc.prototype.b=function(){return Aa(this.coords,Math.round)};function Zc(a,b,c,d,e,f){if(B&&!D("525"))return!0;if(C&&e)return $c(a);if(e&&!d)return!1;if(!A){"number"===typeof b&&(b=ad(b));var h=17==b||18==b||C&&91==b;if((!c||C)&&h||C&&16==b&&(d||f))return!1}if((B||z)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(y&&d&&b==a)return!1;switch(a){case 13:return A?f||e?!1:!(c&&d):!0;case 27:return!(B||z||A)}return A&&(d||e||f)?!1:$c(a)}
function $c(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||(B||z)&&0==a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:case 163:case 58:return!0;case 173:return A;default:return!1}}function ad(a){if(A)a=bd(a);else if(C&&B)switch(a){case 93:a=91}return a}
function bd(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};function X(a,b){U.call(this);a&&cd(this,a,b)}t(X,U);g=X.prototype;g.F=null;g.L=null;g.U=null;g.M=null;g.h=-1;g.s=-1;g.P=!1;
var dd={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},ed={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},fd=!B||D("525"),gd=C&&A;g=X.prototype;
g.fa=function(a){if(B||z)if(17==this.h&&!a.ctrlKey||18==this.h&&!a.altKey||C&&91==this.h&&!a.metaKey)this.s=this.h=-1;-1==this.h&&(a.ctrlKey&&17!=a.a?this.h=17:a.altKey&&18!=a.a?this.h=18:a.metaKey&&91!=a.a&&(this.h=91));fd&&!Zc(a.a,this.h,a.shiftKey,a.ctrlKey,a.altKey,a.metaKey)?this.handleEvent(a):(this.s=ad(a.a),gd&&(this.P=a.altKey))};g.ga=function(a){this.s=this.h=-1;this.P=a.altKey};
g.handleEvent=function(a){var b=a.b,c=b.altKey;if(y&&"keypress"==a.type){var d=this.s;var e=13!=d&&27!=d?b.keyCode:0}else(B||z)&&"keypress"==a.type?(d=this.s,e=0<=b.charCode&&63232>b.charCode&&$c(d)?b.charCode:0):gb&&!B?(d=this.s,e=$c(d)?b.keyCode:0):("keypress"==a.type?(gd&&(c=this.P),b.keyCode==b.charCode?32>b.keyCode?(d=b.keyCode,e=0):(d=this.s,e=b.charCode):(d=b.keyCode||this.s,e=b.charCode||0)):(d=b.keyCode||this.s,e=b.charCode||0),C&&63==e&&224==d&&(d=191));var f=d=ad(d);d?63232<=d&&d in dd?
f=dd[d]:25==d&&a.shiftKey&&(f=9):b.keyIdentifier&&b.keyIdentifier in ed&&(f=ed[b.keyIdentifier]);A&&fd&&"keypress"==a.type&&!Zc(f,this.h,a.shiftKey,a.ctrlKey,c,a.metaKey)||(a=f==this.h,this.h=f,b=new hd(f,e,a,b),b.altKey=c,V(this,b))};g.Eb=function(){return this.F};function cd(a,b,c){a.M&&id(a);a.F=b;a.L=K(a.F,"keypress",a,c);a.U=K(a.F,"keydown",a.fa,c,a);a.M=K(a.F,"keyup",a.ga,c,a)}function id(a){a.L&&(M(a.L),M(a.U),M(a.M),a.L=null,a.U=null,a.M=null);a.F=null;a.h=-1;a.s=-1}
g.i=function(){X.v.i.call(this);id(this)};function hd(a,b,c,d){H.call(this,d);this.type="key";this.a=a;this.g=b;this.repeat=c}t(hd,H);function jd(a,b,c,d,e,f){function h(p){p&&(p.tabIndex=0,Ec(p,k.ba),S(p,"goog-zippy-header"),kd(k,p),ld(k,p))}U.call(this);this.N=e||Zb();this.c=this.N.I(a)||null;this.g=this.N.I(d||null);this.A=n(b)?b:null;this.ba=f||"tab";this.f=this.A||!b?null:this.N.I(b);this.b=1==c;void 0!==c||this.A||(this.g?this.b="none"!=this.g.style.display:this.c&&(this.b=Hc(this.c,"goog-zippy-expanded")));this.V=new T(this);this.u=new X;this.W=new T(this);var k=this;h(this.c);h(this.g);this.C(this.b)}t(jd,U);g=jd.prototype;
g.T=!0;g.S=!0;g.i=function(){jd.v.i.call(this);rb(this.V);rb(this.u);rb(this.W)};g.nb=function(){var a=this.g;return a&&"none"!=a.style.display?a:this.c};g.C=function(a){this.f?this.f.style.display=a?"":"none":a&&this.A&&(this.f=this.A());this.f&&S(this.f,"goog-zippy-content");this.g?(this.c.style.display=a?"none":"",this.g.style.display=a?"":"none"):md(this,a);this.b=a;V(this,new Y("toggle",this,this.b))};
function md(a,b){if(a.c){var c=a.c;b?S(c,"goog-zippy-expanded"):Ic(c,"goog-zippy-expanded");c=a.c;b?Ic(c,"goog-zippy-collapsed"):S(c,"goog-zippy-collapsed");a=a.c;m(b)&&(b=b.join(" "));""===b||void 0==b?(Sb||(Sb={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),b=Sb,"expanded"in b?a.setAttribute("aria-expanded",b.expanded):
a.removeAttribute("aria-expanded")):a.setAttribute("aria-expanded",b)}}g.Ub=function(){return this.S};g.Vb=function(){return this.T};g.nc=function(a){this.S!=a&&((this.S=a)?(ld(this,this.c),ld(this,this.g)):(Mc(this.V),id(this.u)))};g.oc=function(a){this.T!=a&&((this.T=a)?(kd(this,this.c),kd(this,this.g)):Mc(this.W))};function ld(a,b){b&&(cd(a.u,b),a.V.B(a.u,"key",a.na))}function kd(a,b){b&&a.W.B(b,"click",a.ma)}
g.na=function(a){if(13==a.a||32==a.a)this.C(!this.b),V(this,new Y("action",this,this.b,a)),a.preventDefault(),a.stopPropagation()};g.ma=function(a){this.C(!this.b);V(this,new Y("action",this,this.b,a))};function Y(a,b,c,d){G.call(this,a,b);this.a=c;this.b=d||null}t(Y,G);function nd(a,b,c,d,e){d=d||Zb();var f=d.X("DIV",{style:"overflow:hidden"});b=d.I(b);b.parentNode.replaceChild(f,b);f.appendChild(b);this.o=f;this.a=null;jd.call(this,a,b,c,void 0,d,e);a=this.b;this.o.style.display=a?"":"none";md(this,a)}t(nd,jd);g=nd.prototype;g.Kb=500;g.da=function(a){return 1-Math.pow(1-a,3)};g.Ob=function(){return null!=this.a};
g.C=function(a){if(this.b!=a||this.a){"none"==this.o.style.display&&(this.o.style.display="");var b=this.f.offsetHeight;if(this.a){Nb(this.a);Wc(this.a);var c=b-Math.abs(parseInt(this.f.style.marginTop,10))}else c=a?0:b;md(this,a);this.a=new Vc([0,c],[0,a?b:0],500,this.da);K(this.a,["begin","animate","end"],this.ja,!1,this);K(this.a,"begin",r(this.ka,this,a));K(this.a,"end",r(this.la,this,a));a:{a=this.a;if(0==a.a)a.progress=0,a.coords=a.c;else if(1==a.a)break a;Qc(a);b=va();a.b=b;-1==a.a&&(a.b-=
a.duration*a.progress);a.endTime=a.b+a.duration;a.f=a.b;a.progress||a.l("begin");a.l("play");-1==a.a&&a.l("resume");a.a=1;c=a[qa]||(a[qa]=++ra);c in v||(v[c]=a);Rc();Tc(a,b)}}};g.ja=function(a){var b=this.f;b.style.marginTop=a.A-b.offsetHeight+"px"};g.ka=function(a){V(this,new Y("a",this,a))};g.la=function(a){a&&(this.f.style.marginTop="0");Nb(this.a);this.b=a;this.a=null;a||(this.o.style.display="none");V(this,new Y("toggle",this,a));V(this,new Y("b",this,a))};function Z(){var a=N.call(this)||this;a.a=new T;return a}ha(Z,N);Z.prototype.connectedCallback=function(){var a=this.querySelector(".devsite-tracking-question");a&&od(this,a)};Z.prototype.disconnectedCallback=function(){Mc(this.a)};
function od(a,b){S(b.children[0],"devsite-tracking-question-text");for(var c=1;c<b.children.length;c++){var d=b.children[c].children[0];S(d,"devsite-tracking-question-choice-button");S(b.children[c].children[1],"devsite-tracking-question-hidden");Ec(d,"button")}a.a.B(a,"click",function(e){if(Hc(e.target,"devsite-tracking-question-choice-button")&&(e.preventDefault(),e.stopPropagation(),e=e.target)){var f=e.parentNode;if(f){if((e=f.parentNode)&&e.children.length){(new nd(null,e.children[0],!0)).C(!1);
for(var h=1;h<e.children.length;h++)(new nd(null,e.children[h].children[0],!0)).C(!1);1<f.children.length&&(h=f.children[1],e.appendChild(h),Ic(h,"devsite-tracking-question-hidden"),(new nd(null,h,!1)).C(!0))}f=f.getAttribute("data-item-name");if(e){var k=e.getAttribute("data-tracking-dimension");var p=e.getAttribute("data-tracking-gaid")}null!==f&&null!==k&&null!==p&&(a.dispatchEvent(new CustomEvent("devsite-analytics-set-dimension",{detail:{name:k,value:f,gaid:p},bubbles:!0})),a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Tracking Question",action:"click",label:f},bubbles:!0})))}}})}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-tracking-question",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteTrackingQuestion",a)};}).call(this);
