(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var m;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca;
if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={L:!0},fa={};try{fa.__proto__=ea;da=fa.L;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ca;
function ia(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.B=b.prototype}var q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ja(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var r=ja(this);function t(a,b){if(b){var c=r;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&q(c,a,{configurable:!0,writable:!0,value:b})}}
t("Promise",function(a){function b(g){this.b=0;this.c=void 0;this.a=[];var f=this.f();try{g(f.resolve,f.reject)}catch(k){f.reject(k)}}function c(){this.a=null}function d(g){return g instanceof b?g:new b(function(f){f(g)})}if(a)return a;c.prototype.b=function(g){if(null==this.a){this.a=[];var f=this;this.c(function(){f.g()})}this.a.push(g)};var e=r.setTimeout;c.prototype.c=function(g){e(g,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var g=this.a;this.a=[];for(var f=0;f<g.length;++f){var k=
g[f];g[f]=null;try{k()}catch(l){this.f(l)}}}this.a=null};c.prototype.f=function(g){this.c(function(){throw g;})};b.prototype.f=function(){function g(l){return function(n){k||(k=!0,l.call(f,n))}}var f=this,k=!1;return{resolve:g(this.F),reject:g(this.g)}};b.prototype.F=function(g){if(g===this)this.g(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.H(g);else{a:switch(typeof g){case "object":var f=null!=g;break a;case "function":f=!0;break a;default:f=!1}f?this.o(g):this.h(g)}};
b.prototype.o=function(g){var f=void 0;try{f=g.then}catch(k){this.g(k);return}"function"==typeof f?this.J(f,g):this.h(g)};b.prototype.g=function(g){this.i(2,g)};b.prototype.h=function(g){this.i(1,g)};b.prototype.i=function(g,f){if(0!=this.b)throw Error("Cannot settle("+g+", "+f+"): Promise already settled in state"+this.b);this.b=g;this.c=f;this.l()};b.prototype.l=function(){if(null!=this.a){for(var g=0;g<this.a.length;++g)h.b(this.a[g]);this.a=null}};var h=new c;b.prototype.H=function(g){var f=this.f();
g.C(f.resolve,f.reject)};b.prototype.J=function(g,f){var k=this.f();try{g.call(f,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,f){function k(w,D){return"function"==typeof w?function(qa){try{l(w(qa))}catch(ra){n(ra)}}:D}var l,n,v=new b(function(w,D){l=w;n=D});this.C(k(g,l),k(f,n));return v};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.C=function(g,f){function k(){switch(l.b){case 1:g(l.c);break;case 2:f(l.c);break;default:throw Error("Unexpected state: "+
l.b);}}var l=this;null==this.a?h.b(k):this.a.push(k)};b.resolve=d;b.reject=function(g){return new b(function(f,k){k(g)})};b.race=function(g){return new b(function(f,k){for(var l=p(g),n=l.next();!n.done;n=l.next())d(n.value).C(f,k)})};b.all=function(g){var f=p(g),k=f.next();return k.done?d([]):new b(function(l,n){function v(qa){return function(ra){w[qa]=ra;D--;0==D&&l(w)}}var w=[],D=0;do w.push(void 0),D++,d(k.value).C(v(w.length-1),n),k=f.next();while(!k.done)})};return b});
var ka=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ba(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();t("Reflect.construct",function(){return ka});
t("Object.setPrototypeOf",function(a){return a||ha});function la(){la=function(){};r.Symbol||(r.Symbol=ma)}function na(a,b){this.a=a;q(this,"description",{configurable:!0,writable:!0,value:b})}na.prototype.toString=function(){return this.a};var ma=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new na("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function oa(){la();var a=r.Symbol.iterator;a||(a=r.Symbol.iterator=r.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&q(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(aa(this))}});oa=function(){}}function pa(a){oa();a={next:a};a[r.Symbol.iterator]=function(){return this};return a}function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
t("WeakMap",function(a){function b(k){this.a=(f+=Math.random()+1).toString();if(k){k=p(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function e(k){if(!u(k,g)){var l=new c;q(k,g,{value:l})}}function h(k){var l=Object[k];l&&(Object[k]=function(n){if(n instanceof c)return n;e(n);return l(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),n=new a([[k,2],[l,
3]]);if(2!=n.get(k)||3!=n.get(l))return!1;n.delete(k);n.set(l,4);return!n.has(k)&&4==n.get(l)}catch(v){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var f=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.a]=l;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.a]:void 0};b.prototype.has=function(k){return d(k)&&u(k,g)&&u(k[g],this.a)};
b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.a)?delete k[g][this.a]:!1};return b});
t("Map",function(a){function b(){var f={};return f.s=f.next=f.head=f}function c(f,k){var l=f.a;return pa(function(){if(l){for(;l.head!=f.a;)l=l.s;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(f,k){var l=k&&typeof k;"object"==l||"function"==l?h.has(k)?l=h.get(k):(l=""+ ++g,h.set(k,l)):l="p_"+k;var n=f.b[l];if(n&&u(f.b,l))for(f=0;f<n.length;f++){var v=n[f];if(k!==k&&v.key!==v.key||k===v.key)return{id:l,list:n,index:f,j:v}}return{id:l,list:n,
index:-1,j:void 0}}function e(f){this.b={};this.a=b();this.size=0;if(f){f=p(f);for(var k;!(k=f.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),k=new a(p([[f,"s"]]));if("s"!=k.get(f)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),n=l.next();if(n.done||n.value[0]!=f||"s"!=n.value[1])return!1;n=l.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!l.next().done?!1:!0}catch(v){return!1}}())return a;oa();var h=new WeakMap;e.prototype.set=function(f,k){f=0===f?0:f;var l=d(this,f);l.list||(l.list=this.b[l.id]=[]);l.j?l.j.value=k:(l.j={next:this.a,s:this.a.s,head:this.a,key:f,value:k},l.list.push(l.j),this.a.s.next=l.j,this.a.s=l.j,this.size++);return this};e.prototype.delete=function(f){f=d(this,f);return f.j&&f.list?(f.list.splice(f.index,1),f.list.length||delete this.b[f.id],f.j.s.next=f.j.next,f.j.next.s=f.j.s,f.j.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.s=b();this.size=0};e.prototype.has=function(f){return!!d(this,f).j};e.prototype.get=function(f){return(f=d(this,f).j)&&f.value};e.prototype.entries=function(){return c(this,function(f){return[f.key,f.value]})};e.prototype.keys=function(){return c(this,function(f){return f.key})};e.prototype.values=function(){return c(this,function(f){return f.value})};e.prototype.forEach=function(f,k){for(var l=this.entries(),n;!(n=l.next()).done;)n=
n.value,f.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});t("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(f){return f};var e=[],h="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof h){b=h.call(b);for(var g=0;!(h=b.next()).done;)e.push(c.call(d,h.value,g++))}else for(h=b.length,g=0;g<h;g++)e.push(c.call(d,b[g],g));return e}});var x=this||self;
function sa(a){a=a.split(".");for(var b=x,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}function ta(){}
function y(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function z(a){return"array"==y(a)}function ua(a){var b=y(a);return"array"==b||"object"==b&&"number"==typeof a.length}function A(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function va(a,b,c){return a.call.apply(a.bind,arguments)}
function wa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function B(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?B=va:B=wa;return B.apply(null,arguments)}
function xa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var ya=Date.now||function(){return+new Date};function za(a,b){function c(){}c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.P=function(d,e,h){for(var g=Array(arguments.length-2),f=2;f<arguments.length;f++)g[f-2]=arguments[f];return b.prototype[e].apply(d,g)}};var Aa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ba=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,h=0;h<d;h++)h in e&&b.call(c,e[h],h,a)};
function Ca(a){return Array.prototype.concat.apply([],arguments)}function Da(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Ea=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function C(a,b){return-1!=a.indexOf(b)}function Fa(a,b){return a<b?-1:a>b?1:0};var E;a:{var Ga=x.navigator;if(Ga){var Ha=Ga.userAgent;if(Ha){E=Ha;break a}}E=""};function Ia(a,b,c){for(var d in a)b.call(c,a[d],d,a)};function Ja(a){Ja[" "](a);return a}Ja[" "]=ta;var Ka=C(E,"Opera"),F=C(E,"Trident")||C(E,"MSIE"),La=C(E,"Edge"),Ma=C(E,"Gecko")&&!(C(E.toLowerCase(),"webkit")&&!C(E,"Edge"))&&!(C(E,"Trident")||C(E,"MSIE"))&&!C(E,"Edge"),G=C(E.toLowerCase(),"webkit")&&!C(E,"Edge"),Na=C(E,"Macintosh");function Oa(){var a=x.document;return a?a.documentMode:void 0}var Pa;
a:{var Qa="",Ra=function(){var a=E;if(Ma)return/rv:([^\);]+)(\)|;)/.exec(a);if(La)return/Edge\/([\d\.]+)/.exec(a);if(F)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(G)return/WebKit\/(\S+)/.exec(a);if(Ka)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ra&&(Qa=Ra?Ra[1]:"");if(F){var Sa=Oa();if(null!=Sa&&Sa>parseFloat(Qa)){Pa=String(Sa);break a}}Pa=Qa}var Ta=Pa,Ua={},Va;Va=x.document&&F?Oa():void 0;var Wa="StopIteration"in x?x.StopIteration:{message:"StopIteration",stack:""};function Xa(){}Xa.prototype.next=function(){throw Wa;};Xa.prototype.a=function(){return this};function H(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof H)for(c=a.u(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}m=H.prototype;m.m=function(){I(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};m.u=function(){I(this);return this.a.concat()};
m.la=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(J(this.b,c)&&this.b[c]==a)return!0}return!1};m.R=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||Ya;I(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function Ya(a,b){return a===b}m.ma=function(){return 0==this.c};m.ka=function(){this.b={};this.f=this.c=this.a.length=0};
function I(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];J(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],J(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}m.get=function(a,b){return J(this.b,a)?this.b[a]:b};m.set=function(a,b){J(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};m.forEach=function(a,b){for(var c=this.u(),d=0;d<c.length;d++){var e=c[d],h=this.get(e);a.call(b,h,e,this)}};
m.za=function(){for(var a=new H,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};m.ya=function(){I(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};m.V=function(){return Za(this,!0)};m.Y=function(){return Za(this,!1)};function Za(a,b){I(a);var c=0,d=a.f,e=new Xa;e.next=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw Wa;var h=a.a[c++];return b?h:a.b[h]};return e}
function J(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function $a(a){if(a.m&&"function"==typeof a.m)return a.m();if("string"===typeof a)return a.split("");if(ua(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function ab(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(ua(a)||"string"===typeof a)Ba(a,b,c);else{if(a.u&&"function"==typeof a.u)var d=a.u();else if(a.m&&"function"==typeof a.m)d=void 0;else if(ua(a)||"string"===typeof a){d=[];for(var e=a.length,h=0;h<e;h++)d.push(h)}else for(h in d=[],e=0,a)d[e++]=h;e=$a(a);h=e.length;for(var g=0;g<h;g++)b.call(c,e[g],d&&d[g],a)}};var bb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/\\#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function cb(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var h=a[c].substring(0,d);e=a[c].substring(d+1)}else h=a[c];b(h,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function K(a,b){this.b=this.l=this.h="";this.f=null;this.i=this.c="";this.g=this.o=!1;if(a instanceof K){this.g=void 0!==b?b:a.g;db(this,a.h);var c=a.l;L(this);this.l=c;c=a.b;L(this);this.b=c;eb(this,a.f);c=a.c;L(this);this.c=c;M(this,fb(a.a));a=a.i;L(this);this.i=a}else a&&(c=String(a).match(bb))?(this.g=!!b,db(this,c[1]||"",!0),a=c[2]||"",L(this),this.l=N(a),a=c[3]||"",L(this),this.b=N(a,!0),eb(this,c[4]),a=c[5]||"",L(this),this.c=N(a,!0),M(this,c[6]||"",!0),a=c[7]||"",L(this),this.i=N(a)):(this.g=
!!b,this.a=new O(null,this.g))}m=K.prototype;m.toString=function(){var a=[],b=this.h;b&&a.push(P(b,gb,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.l)&&a.push(P(b,gb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(P(c,"/"==c.charAt(0)?hb:ib,!0));(c=this.a.toString())&&a.push("?",c);(c=this.i)&&a.push("#",P(c,jb));return a.join("")};
m.resolve=function(a){var b=new K(this),c=!!a.h;c?db(b,a.h):c=!!a.l;if(c){var d=a.l;L(b);b.l=d}else c=!!a.b;c?(d=a.b,L(b),b.b=d):c=null!=a.f;d=a.c;if(c)eb(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(C(e,"./")||C(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var h=[],g=0;g<e.length;){var f=e[g++];"."==f?d&&g==e.length&&h.push(""):".."==f?((1<h.length||1==h.length&&""!=
h[0])&&h.pop(),d&&g==e.length&&h.push("")):(h.push(f),d=!0)}d=h.join("/")}else d=e}c?(L(b),b.c=d):c=""!==a.a.toString();c?M(b,fb(a.a)):c=!!a.i;c&&(a=a.i,L(b),b.i=a);return b};function db(a,b,c){L(a);a.h=c?N(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))}function eb(a,b){L(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function M(a,b,c){L(a);b instanceof O?(a.a=b,kb(a.a,a.g)):(c||(b=P(b,lb)),a.a=new O(b,a.g));return a}m.wa=function(a,b){return M(this,a,b)};
m.T=function(){return N(this.a.toString())};m.da=function(){return this.a.toString()};m.va=function(a,b){L(this);z(b)||(b=[String(b)]);mb(this.a,a,b);return this};m.X=function(a){return this.a.m(a)};m.W=function(a){return this.a.get(a)};m.na=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};
m.ta=function(){L(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^ya()).toString(36);L(this);this.a.set("zx",a);return this};m.ea=function(a){L(this);Q(this.a,a);return this};m.xa=function(a){this.o=a;return this};m.oa=function(){return this.o};function L(a){if(a.o)throw Error("Tried to modify a read-only Uri");}m.fa=function(a){this.g=a;this.a&&kb(this.a,a);return this};function nb(a){return a instanceof K?new K(a):new K(a,void 0)}
function N(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function P(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,ob),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function ob(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var gb=/[#\/\?@]/g,ib=/[#\?:]/g,hb=/[#\?]/g,lb=/[#\?@]/g,jb=/#/g;function O(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}
function R(a){a.a||(a.a=new H,a.b=0,a.c&&cb(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}m=O.prototype;m.ba=function(){R(this);return this.b};m.add=function(a,b){R(this);this.c=null;a=S(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};function Q(a,b){R(a);b=S(a,b);J(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,J(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&I(a)))}m.Z=function(){this.a=this.c=null;this.b=0};
m.ca=function(){R(this);return 0==this.b};function pb(a,b){R(a);b=S(a,b);return J(a.a.b,b)}m.$=function(a){var b=this.m();return 0<=Aa(b,a)};m.forEach=function(a,b){R(this);this.a.forEach(function(c,d){Ba(c,function(e){a.call(b,e,d,this)},this)},this)};m.u=function(){R(this);for(var a=this.a.m(),b=this.a.u(),c=[],d=0;d<b.length;d++)for(var e=a[d],h=0;h<e.length;h++)c.push(b[d]);return c};
m.m=function(a){R(this);var b=[];if("string"===typeof a)pb(this,a)&&(b=Ca(b,this.a.get(S(this,a))));else{a=this.a.m();for(var c=0;c<a.length;c++)b=Ca(b,a[c])}return b};m.set=function(a,b){R(this);this.c=null;a=S(this,a);pb(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};m.get=function(a,b){if(!a)return b;a=this.m(a);return 0<a.length?String(a[0]):b};function mb(a,b,c){Q(a,b);0<c.length&&(a.c=null,a.a.set(S(a,b),Da(c)),a.b+=c.length)}
m.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.u(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.m(d);for(var h=0;h<d.length;h++){var g=e;""!==d[h]&&(g+="="+encodeURIComponent(String(d[h])));a.push(g)}}return this.c=a.join("&")};m.S=function(a){R(this);this.a.forEach(function(b,c){0<=Aa(a,c)||Q(this,c)},this);return this};function fb(a){var b=new O;b.c=a.c;a.a&&(b.a=new H(a.a),b.b=a.b);return b}
function S(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function kb(a,b){b&&!a.f&&(R(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Q(this,d),mb(this,e,c))},a));a.f=b}m.aa=function(a){for(var b=0;b<arguments.length;b++)ab(arguments[b],function(c,d){this.add(d,c)},this)};var qb={};function rb(a,b){var c=qb[a];if(void 0!==c&&(!c.G||Date.now()<=c.G+3E5))return c.p;c=new Promise(function(e,h){b.onload=function(){return e(b)};b.onerror=function(g){b.parentNode&&b.parentNode.removeChild(b);h(g)};document.head.appendChild(b)});var d={G:0,p:c};c.catch(function(){return d.G=+new Date});qb[a]=d;return c};var sb=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(sb&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function T(a){var b=HTMLElement.call(this)||this;a&&tb(a);return b}ia(T,HTMLElement);T.prototype.i=function(){console.warn(this.tagName,"has not implemented update")};T.prototype.g=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
T.prototype.h=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function tb(a){"string"===typeof a&&(a=[a]);document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a}))};var ub=new Map;function U(a){var b=T.call(this)||this;a&&tb(a);return b}ia(U,T);U.prototype.connectedCallback=function(){var a=this.constructor,b=ub.get(a);b?console.error("can't add duplicate element to page: "+b.tagName):ub.set(a,this)};U.prototype.disconnectedCallback=function(){var a=this.constructor;ub.get(a)===this&&ub.delete(a)};U.prototype.disconnectedCallback=U.prototype.disconnectedCallback;U.prototype.connectedCallback=U.prototype.connectedCallback;function V(){this.v=this.v;this.b=this.b}m=V.prototype;m.v=!1;m.N=function(){return this.v};m.U=V.prototype.N;m.I=function(){this.v||(this.v=!0,this.w())};m.ua=function(a){a=xa(vb,a);this.v?a():(this.b||(this.b=[]),this.b.push(a))};m.w=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function vb(a){a&&"function"==typeof a.I&&a.I()};function wb(a,b){this.type=a;this.b=this.target=b;this.defaultPrevented=this.f=!1}wb.prototype.g=function(){this.f=!0};wb.prototype.c=function(){this.defaultPrevented=!0};var xb=!F||9<=Number(Va),yb=!F||9<=Number(Va),zb;
if(zb=F){var Ab;if(Object.prototype.hasOwnProperty.call(Ua,"9"))Ab=Ua["9"];else{for(var Bb=0,Cb=Ea(String(Ta)).split("."),Db=Ea("9").split("."),Eb=Math.max(Cb.length,Db.length),Fb=0;0==Bb&&Fb<Eb;Fb++){var Gb=Cb[Fb]||"",Hb=Db[Fb]||"";do{var W=/(\d*)(\D*)(.*)/.exec(Gb)||["","","",""],X=/(\d*)(\D*)(.*)/.exec(Hb)||["","","",""];if(0==W[0].length&&0==X[0].length)break;Bb=Fa(0==W[1].length?0:parseInt(W[1],10),0==X[1].length?0:parseInt(X[1],10))||Fa(0==W[2].length,0==X[2].length)||Fa(W[2],X[2]);Gb=W[3];
Hb=X[3]}while(0==Bb)}Ab=Ua["9"]=0<=Bb}zb=!Ab}var Ib=zb,Jb=function(){if(!x.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{x.addEventListener("test",ta,b),x.removeEventListener("test",ta,b)}catch(c){}return a}();function Y(a,b){wb.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.o=this.l=0;this.key="";this.h=this.i=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.F=null;this.H=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(Ma){a:{try{Ja(b.nodeName);
var e=!0;break a}catch(h){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.l=G||void 0!==a.offsetX?a.offsetX:a.layerX,this.o=G||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.i=a.keyCode||0;this.key=a.key||"";this.h=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.H=Na?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Kb[a.pointerType]||"";this.F=a.state;this.a=a;a.defaultPrevented&&this.c()}}za(Y,wb);var Lb=[1,4,2],Kb={2:"touch",3:"pen",4:"mouse"};
Y.prototype.Ba=function(){return(xb?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Lb[0]))&&!(G&&Na&&this.ctrlKey)};Y.prototype.g=function(){Y.B.g.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};Y.prototype.c=function(){Y.B.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ib)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};Y.prototype.J=function(){return this.a};var Mb="closure_listenable_"+(1E6*Math.random()|0),Nb=0;function Ob(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Nb;this.A=this.D=!1}function Pb(a){a.A=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Qb(a){this.src=a;this.a={};this.b=0}Qb.prototype.c=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};Qb.prototype.add=function(a,b,c,d,e){var h=a.toString();a=this.a[h];a||(a=this.a[h]=[],this.b++);var g=Rb(a,b,d,e);-1<g?(b=a[g],c||(b.D=!1)):(b=new Ob(b,this.src,h,!!d,e),b.D=c,a.push(b));return b};function Sb(a,b){var c=b.type;if(c in a.a){var d=a.a[c],e=Aa(d,b),h;(h=0<=e)&&Array.prototype.splice.call(d,e,1);h&&(Pb(b),0==a.a[c].length&&(delete a.a[c],a.b--))}}
function Tb(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Rb(a,c,d,e));return-1<b?a[b]:null}function Rb(a,b,c,d){for(var e=0;e<a.length;++e){var h=a[e];if(!h.A&&h.listener==b&&h.capture==!!c&&h.b==d)return e}return-1};var Ub="closure_lm_"+(1E6*Math.random()|0),Vb={},Wb=0;function Xb(a,b,c,d,e){if(d&&d.once)return Yb(a,b,c,d,e);if(z(b)){for(var h=0;h<b.length;h++)Xb(a,b[h],c,d,e);return null}c=Zb(c);return a&&a[Mb]?a.listen(b,c,A(d)?!!d.capture:!!d,e):$b(a,b,c,!1,d,e)}
function $b(a,b,c,d,e,h){if(!b)throw Error("Invalid event type");var g=A(e)?!!e.capture:!!e,f=ac(a);f||(a[Ub]=f=new Qb(a));c=f.add(b,c,d,g,h);if(c.a)return c;d=bc();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Jb||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(cc(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Wb++;return c}
function bc(){var a=dc,b=yb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Yb(a,b,c,d,e){if(z(b)){for(var h=0;h<b.length;h++)Yb(a,b[h],c,d,e);return null}c=Zb(c);return a&&a[Mb]?a.c.add(String(b),c,!0,A(d)?!!d.capture:!!d,e):$b(a,b,c,!0,d,e)}
function ec(a){if("number"!==typeof a&&a&&!a.A){var b=a.src;if(b&&b[Mb])Sb(b.c,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(cc(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Wb--;(c=ac(b))?(Sb(c,a),0==c.b&&(c.src=null,b[Ub]=null)):Pb(a)}}}function cc(a){return a in Vb?Vb[a]:Vb[a]="on"+a}
function fc(a,b,c,d){var e=!0;if(a=ac(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var h=b[a];h&&h.capture==c&&!h.A&&(h=gc(h,d),e=e&&!1!==h)}return e}function gc(a,b){var c=a.listener,d=a.b||a.src;a.D&&ec(a);return c.call(d,b)}
function dc(a,b){if(a.A)return!0;if(!yb){var c=b||sa("window.event");b=new Y(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.f&&0<=e;e--){b.b=c[e];var h=fc(c[e],a,!0,b);d=d&&h}for(e=0;!b.f&&e<c.length;e++)b.b=c[e],h=fc(c[e],a,!1,b),d=d&&h}return d}return gc(a,new Y(b,this))}
function ac(a){a=a[Ub];return a instanceof Qb?a:null}var hc="__closure_events_fn_"+(1E9*Math.random()>>>0);function Zb(a){if("function"==y(a))return a;a[hc]||(a[hc]=function(b){return a.handleEvent(b)});return a[hc]};function ic(a,b){if("function"!=y(a))if(a&&"function"==typeof a.handleEvent)a=B(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:x.setTimeout(a,b||0)};function jc(a,b,c){V.call(this);this.o=null!=c?B(a,c):a;this.l=b;this.i=B(this.O,this);this.c=!1;this.f=0;this.g=this.a=null;this.h=[]}za(jc,V);m=jc.prototype;m.M=function(a){this.h=arguments;this.c=!1;this.a?this.g=ya()+this.l:this.a=ic(this.i,this.l)};m.ga=function(){++this.f};m.ha=function(){this.f&&(--this.f,!this.f&&this.c&&(this.c=!1,this.o.apply(null,this.h)))};m.w=function(){this.a&&(x.clearTimeout(this.a),this.a=null);this.g=null;this.c=!1;this.h=[];jc.B.w.call(this)};
m.O=function(){this.g?(this.a=ic(this.i,this.g-ya()),this.g=null):(this.a=null,this.f?this.c=!0:(this.c=!1,this.o.apply(null,this.h)))};function kc(a){V.call(this);this.c=a;this.a={}}za(kc,V);var lc=[];m=kc.prototype;m.listen=function(a,b,c,d){return mc(this,a,b,c,d)};m.qa=function(a,b,c,d,e){return mc(this,a,b,c,d,e)};function mc(a,b,c,d,e,h){z(c)||(c&&(lc[0]=c.toString()),c=lc);for(var g=0;g<c.length;g++){var f=Xb(b,c[g],d||a.handleEvent,e||!1,h||a.c||a);if(!f)break;a.a[f.key]=f}return a}m.ja=function(a,b,c,d){return nc(this,a,b,c,d)};m.pa=function(a,b,c,d,e){return nc(this,a,b,c,d,e)};
function nc(a,b,c,d,e,h){if(z(c))for(var g=0;g<c.length;g++)nc(a,b,c[g],d,e,h);else{b=Yb(b,c,d||a.handleEvent,e,h||a.c||a);if(!b)return a;a.a[b.key]=b}return a}m.ra=function(a,b,c,d){b.listen(a,c,d,this.c||this,this);return this};m.sa=function(a,b,c,d,e){b.listen(a,c,d,e||this.c||this,this);return this};m.ia=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
m.K=function(a,b,c,d,e){if(z(b))for(var h=0;h<b.length;h++)this.K(a,b[h],c,d,e);else c=c||this.handleEvent,d=A(d)?!!d.capture:!!d,e=e||this.c||this,c=Zb(c),d=!!d,b=a&&a[Mb]?Tb(a.c,String(b),c,d,e):a?(a=ac(a))?Tb(a,b,c,d,e):null:null,b&&(ec(b),delete this.a[b.key])};m.Aa=function(a,b,c,d,e){b.K(a,c,d,e||this.c||this,this);return this};function oc(a){Ia(a.a,function(b,c){this.a.hasOwnProperty(c)&&ec(b)},a);a.a={}}m.w=function(){kc.B.w.call(this);oc(this)};
m.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var pc=null,qc=null,rc=new Map([[".mdc-button.mdc-ripple","MDCRipple"],[".mdc-list","MDCList"],[".mdc-menu","MDCMenu"],[".mdc-menu-surface","MDCMenuSurface"],[".mdc-switch","MDCSwitch"],[".mdc-text-field","MDCTextField"]]);function Z(){var a=U.call(this)||this;a.a=new kc(a);a.b=-1;a.f=new jc(function(){sc(a)},20);return a}ia(Z,U);Z.prototype.connectedCallback=function(){var a=this;tc(this);Promise.all([uc(),vc()]).then(function(){sc(a)}).catch(function(){pc=qc=null})};
function tc(a){a.a.listen(document.body,["devsite-page-changed","devsite-content-updated"],function(){a.f.M()})}function uc(){if(pc)return pc;var a=new URL(DevsiteApp.getStaticPath()+"/js/material-components-web/material-components-web.min.js",document.location.origin);var b=void 0===b?null:b;a=nb(a.href);var c=document.createElement("script");c.src=a.toString();b&&(c.type=b);return pc=rb(a.toString(),c)}
function vc(){if(qc)return qc;var a=new URL(DevsiteApp.getStaticPath()+"/js/material-components-web/material-components-web.min.css",document.location.origin);a=nb(a.href);var b=document.createElement("link");b.setAttribute("rel","stylesheet");b.setAttribute("type","text/css");b.setAttribute("href",a.toString());return qc=rb(a.toString(),b)}
function sc(a,b){b=void 0===b?0:b;window.clearTimeout(a.b);1E3<b?console.warn("Failed to load mdc"):sa("mdc")?(document.body.hasAttribute("mdc--ready")||window.requestAnimationFrame(function(){document.body.setAttribute("mdc--ready","")}),wc(),mdc.autoInit(document.body,function(){})):(a.b=window.setTimeout(function(){sc(a,b+1)},5),document.body.removeAttribute("mdc--ready"))}
function wc(){Array.from(rc.keys()).forEach(function(a){var b=rc.get(a);Array.from(document.querySelectorAll(a+":not([data-mdc-auto-init]):not([skip-auto-init])")).forEach(function(c){c.setAttribute("data-mdc-auto-init",b)})})}Z.prototype.disconnectedCallback=function(){oc(this.a)};Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-mdc",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteMDC",a)};}).call(this);
