(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function k(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var l="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},m;if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var p={w:!0},q={};try{q.__proto__=p;n=q.w;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=m;
function t(a,b){a.prototype=l(b.prototype);a.prototype.constructor=a;if(r)r(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.u=b.prototype}function u(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}
var v=u(this),w="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function x(a,b){if(b){var c=v;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&w(c,a,{configurable:!0,writable:!0,value:b})}}x("globalThis",function(a){return a||v});
var y=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=l(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();x("Reflect.construct",function(){return y});
x("Object.setPrototypeOf",function(a){return a||r});x("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push(b[d]);return c}});
x("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var f=0;!(g=b.next()).done;)e.push(c.call(d,g.value,f++))}else for(g=b.length,f=0;f<g;f++)e.push(c.call(d,b[f],f));return e}});var z=this||self;
function A(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function B(a,b,c){return a.call.apply(a.bind,arguments)}function C(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}
function D(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?D=B:D=C;return D.apply(null,arguments)}function E(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var F=Date.now||function(){return+new Date};
function G(a,b){function c(){}c.prototype=b.prototype;a.u=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.M=function(d,e,g){for(var f=Array(arguments.length-2),h=2;h<arguments.length;h++)f[h-2]=arguments[h];return b.prototype[e].apply(d,f)}};var H=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(H&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function I(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}t(I,HTMLElement);I.prototype.i=function(){console.warn(this.tagName,"has not implemented update")};I.prototype.g=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
I.prototype.h=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function J(){this.c=this.c;this.a=this.a}J.prototype.c=!1;J.prototype.A=function(){return this.c};J.prototype.C=J.prototype.A;J.prototype.l=function(){this.c||(this.c=!0,this.j())};J.prototype.H=function(a){a=E(K,a);this.c?a():(this.a||(this.a=[]),this.a.push(a))};J.prototype.j=function(){if(this.a)for(;this.a.length;)this.a.shift()()};function K(a){a&&"function"==typeof a.l&&a.l()};var L=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};function M(a,b){var c=/\d+|\.\d+|\D+/g;if(a==b)return 0;if(!a)return-1;if(!b)return 1;for(var d=a.toLowerCase().match(c),e=b.toLowerCase().match(c),g=Math.min(d.length,e.length),f=0;f<g;f++){c=d[f];var h=e[f];if(c!=h)return a=parseInt(c,10),!isNaN(a)&&(b=parseInt(h,10),!isNaN(b)&&a-b)?a-b:c<h?-1:1}return d.length!=e.length?d.length-e.length:a<b?-1:1};function N(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return O(a,function(g){var f;(f=!e||g.nodeName==e)&&!(f=!c)&&(f="string"===typeof g.className)&&(f=0<=L(g.className.split(/\s+/),c));return f},d)}function O(a,b,c){for(var d=0;a&&(null==c||d<=c);){if(b(a))return a;a=a.parentNode;d++}return null};function P(a,b){if("function"!=A(a))if(a&&"function"==typeof a.handleEvent)a=D(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:z.setTimeout(a,b||0)};function Q(a,b,c){J.call(this);this.v=null!=c?D(a,c):a;this.s=b;this.m=D(this.B,this);this.f=!1;this.g=0;this.h=this.b=null;this.i=[]}G(Q,J);Q.prototype.o=function(a){this.i=arguments;this.f=!1;this.b?this.h=F()+this.s:this.b=P(this.m,this.s)};Q.prototype.F=function(){++this.g};Q.prototype.G=function(){this.g&&(--this.g,!this.g&&this.f&&(this.f=!1,this.v.apply(null,this.i)))};Q.prototype.j=function(){this.b&&(z.clearTimeout(this.b),this.b=null);this.h=null;this.f=!1;this.i=[];Q.u.j.call(this)};
Q.prototype.B=function(){this.h?(this.b=P(this.m,this.h-F()),this.h=null):(this.b=null,this.g?this.f=!0:(this.f=!1,this.v.apply(null,this.i)))};var R={D:"ancestor",I:"reset",J:"sort-attribute",K:"sort-descending",L:"sort-elements"};function S(){var a=I.call(this)||this;a.a=null;a.c=!1;a.f=new Q(function(){T(a)},10);a.b=null;return a}t(S,I);
S.prototype.connectedCallback=function(){if(!this.c){var a=this.querySelector(".devsite-sort");if(a){var b=Object.values(R);var c="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];b=c?c.call(b):{next:k(b)};for(c=b.next();!c.done;c=b.next())c=c.value,a.hasAttribute(c)&&(this.setAttribute(c,a.getAttribute(c)),a.removeAttribute(c));a.classList.remove(".devsite-sort")}this.a=this.firstElementChild;if(this.getAttribute("ancestor")){(a=N(this,this.getAttribute("ancestor")))||(a=this.getAttribute("ancestor"),
a=N(this,null,a,void 0));var d=a}d&&d.querySelector("devsite-pagination")&&(this.b=d.querySelector("devsite-pagination"));this.c=!0}this.f.o()};S.prototype.attributeChangedCallback=function(a){"sort-elements"!==a&&"sort-descending"!==a&&"sort-attribute"!==a||this.f.o()};
function T(a){if(a.a){if(a.hasAttribute("sort-elements")){var b="devsite-sort > * > "+a.getAttribute("sort-elements");b=Array.from(a.a.querySelectorAll(b))}else b=Array.from(a.a.children);var c=a.hasAttribute("sort-attribute")?a.getAttribute("sort-attribute"):"",d=a.hasAttribute("sort-descending")?-1:1;b.sort(function(e,g){var f=e.hasAttribute(c)&&e.getAttribute(c),h=g.hasAttribute(c)&&g.getAttribute(c);return f&&h?M(f,h)*d:f?-1*d:h?d:M(e.innerText,g.innerText)*d}).forEach(function(e){a.a.appendChild(e)});
U(a.b)}}function U(a){a&&(a.hasAttribute("reset")?a.removeAttribute("reset"):a.setAttribute("reset",""))}v.Object.defineProperties(S,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["sort-elements","sort-descending","sort-attribute"]}}});S.prototype.attributeChangedCallback=S.prototype.attributeChangedCallback;S.prototype.connectedCallback=S.prototype.connectedCallback;try{window.customElements.define("devsite-sort",S)}catch(a){console.warn("devsite.app.customElement.DevsiteSort",a)};}).call(this);
