(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={ua:!0},ha={};try{ha.__proto__=fa;ea=ha.ua;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function ja(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ea=b.prototype}function ka(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}
var n=ka(this),la="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function q(a,b){if(b){var c=n;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&la(c,a,{configurable:!0,writable:!0,value:b})}}
q("Promise",function(a){function b(h){this.b=0;this.g=void 0;this.a=[];var k=this.c();try{h(k.resolve,k.reject)}catch(l){k.reject(l)}}function c(){this.a=null}function d(h){return h instanceof b?h:new b(function(k){k(h)})}if(a)return a;c.prototype.b=function(h){if(null==this.a){this.a=[];var k=this;this.c(function(){k.g()})}this.a.push(h)};var e=n.setTimeout;c.prototype.c=function(h){e(h,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var h=this.a;this.a=[];for(var k=0;k<h.length;++k){var l=
h[k];h[k]=null;try{l()}catch(m){this.f(m)}}}this.a=null};c.prototype.f=function(h){this.c(function(){throw h;})};b.prototype.c=function(){function h(m){return function(p){l||(l=!0,m.call(k,p))}}var k=this,l=!1;return{resolve:h(this.N),reject:h(this.f)}};b.prototype.N=function(h){if(h===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(h instanceof b)this.O(h);else{a:switch(typeof h){case "object":var k=null!=h;break a;case "function":k=!0;break a;default:k=!1}k?this.v(h):this.h(h)}};
b.prototype.v=function(h){var k=void 0;try{k=h.then}catch(l){this.f(l);return}"function"==typeof k?this.P(k,h):this.h(h)};b.prototype.f=function(h){this.i(2,h)};b.prototype.h=function(h){this.i(1,h)};b.prototype.i=function(h,k){if(0!=this.b)throw Error("Cannot settle("+h+", "+k+"): Promise already settled in state"+this.b);this.b=h;this.g=k;this.j()};b.prototype.j=function(){if(null!=this.a){for(var h=0;h<this.a.length;++h)f.b(this.a[h]);this.a=null}};var f=new c;b.prototype.O=function(h){var k=this.c();
h.G(k.resolve,k.reject)};b.prototype.P=function(h,k){var l=this.c();try{h.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(h,k){function l(H,u){return"function"==typeof H?function(na){try{m(H(na))}catch(ya){p(ya)}}:u}var m,p,r=new b(function(H,u){m=H;p=u});this.G(l(h,m),l(k,p));return r};b.prototype.catch=function(h){return this.then(void 0,h)};b.prototype.G=function(h,k){function l(){switch(m.b){case 1:h(m.g);break;case 2:k(m.g);break;default:throw Error("Unexpected state: "+
m.b);}}var m=this;null==this.a?f.b(l):this.a.push(l)};b.resolve=d;b.reject=function(h){return new b(function(k,l){l(h)})};b.race=function(h){return new b(function(k,l){for(var m=ba(h),p=m.next();!p.done;p=m.next())d(p.value).G(k,l)})};b.all=function(h){var k=ba(h),l=k.next();return l.done?d([]):new b(function(m,p){function r(na){return function(ya){H[na]=ya;u--;0==u&&m(H)}}var H=[],u=0;do H.push(void 0),u++,d(l.value).G(r(H.length-1),p),l=k.next();while(!l.done)})};return b});
function ma(){ma=function(){};n.Symbol||(n.Symbol=oa)}function pa(a,b){this.a=a;la(this,"description",{configurable:!0,writable:!0,value:b})}pa.prototype.toString=function(){return this.a};var oa=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new pa("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function qa(){ma();var a=n.Symbol.iterator;a||(a=n.Symbol.iterator=n.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&la(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ra(aa(this))}});qa=function(){}}function ra(a){qa();a={next:a};a[n.Symbol.iterator]=function(){return this};return a}function sa(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}
function ta(){this.h=!1;this.c=null;this.i=void 0;this.a=1;this.f=this.g=0;this.j=this.b=null}function ua(a){if(a.h)throw new TypeError("Generator is already running");a.h=!0}g=ta.prototype;g.K=function(a){this.i=a};function va(a,b){a.b={xa:b,Y:!0};a.a=a.g||a.f}g.return=function(a){this.b={return:a};this.a=this.f};g.bd=function(a){this.b={F:a};this.a=this.f};g.Bf=function(a,b){a=ba(a);var c=a.next();sa(c);if(c.done)this.i=c.value,this.a=b;else return this.c=a,a=c.value,this.a=b,{value:a}};
g.F=function(a){this.a=a};g.Rd=function(a){this.g=0;this.f=a||0};g.eb=function(a,b,c){c?this.j[c]=this.b:this.j=[this.b];this.g=a||0;this.f=b||0};g.dd=function(a,b){b=this.j.splice(b||0)[0];(b=this.b=this.b||b)?b.Y?this.a=this.g||this.f:void 0!=b.F&&this.f<b.F?(this.a=b.F,this.b=null):this.a=this.f:this.a=a};g.nb=function(a){return new wa(a)};function wa(a){this.b=a;this.a=[];for(var b in a)this.a.push(b);this.a.reverse()}
wa.prototype.c=function(){for(;0<this.a.length;){var a=this.a.pop();if(a in this.b)return a}return null};function xa(a){this.a=new ta;this.b=a}function za(a,b){ua(a.a);var c=a.a.c;if(c)return Aa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return Ba(a)}function Aa(a,b,c,d){try{var e=b.call(a.a.c,c);sa(e);if(!e.done)return a.a.h=!1,e;var f=e.value}catch(h){return a.a.c=null,va(a.a,h),Ba(a)}a.a.c=null;d.call(a.a,f);return Ba(a)}
function Ba(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.h=!1,{value:b.value,done:!1}}catch(c){a.a.i=void 0,va(a.a,c)}a.a.h=!1;if(a.a.b){b=a.a.b;a.a.b=null;if(b.Y)throw b.xa;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function Ca(a){this.next=function(b){ua(a.a);a.a.c?b=Aa(a,a.a.c.next,b,a.a.K):(a.a.K(b),b=Ba(a));return b};this.throw=function(b){ua(a.a);a.a.c?b=Aa(a,a.a.c["throw"],b,a.a.K):(va(a.a,b),b=Ba(a));return b};this.return=function(b){return za(a,b)};qa();this[Symbol.iterator]=function(){return this}}function Da(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}new Promise(function(d,e){function f(h){h.done?d(h.value):Promise.resolve(h.value).then(b,c).then(f,e)}f(a.next())})}
q("globalThis",function(a){return a||n});function Ea(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
q("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=Ea(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var h=0;h<f&&c<e;)if(d[c++]!=b[h++])return!1;return h>=f}});q("String.prototype.repeat",function(a){return a?a:function(b){var c=Ea(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
function Fa(a,b){qa();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}
q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});q("Array.prototype.keys",function(a){return a?a:function(){return Fa(this,function(b){return b})}});
q("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});q("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==Ea(this,b,"includes").indexOf(b,c||0)}});
var Ga=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ca(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();q("Reflect.construct",function(){return Ga});
q("Object.setPrototypeOf",function(a){return a||ia});function Ha(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
q("WeakMap",function(a){function b(l){this.a=(k+=Math.random()+1).toString();if(l){l=ba(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function e(l){if(!Ha(l,h)){var m=new c;la(l,h,{value:m})}}function f(l){var m=Object[l];m&&(Object[l]=function(p){if(p instanceof c)return p;e(p);return m(p)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),p=new a([[l,2],
[m,3]]);if(2!=p.get(l)||3!=p.get(m))return!1;p.delete(l);p.set(m,4);return!p.has(l)&&4==p.get(m)}catch(r){return!1}}())return a;var h="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var k=0;b.prototype.set=function(l,m){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!Ha(l,h))throw Error("WeakMap key fail: "+l);l[h][this.a]=m;return this};b.prototype.get=function(l){return d(l)&&Ha(l,h)?l[h][this.a]:void 0};b.prototype.has=function(l){return d(l)&&Ha(l,h)&&Ha(l[h],
this.a)};b.prototype.delete=function(l){return d(l)&&Ha(l,h)&&Ha(l[h],this.a)?delete l[h][this.a]:!1};return b});
q("Map",function(a){function b(){var k={};return k.o=k.next=k.head=k}function c(k,l){var m=k.a;return ra(function(){if(m){for(;m.head!=k.a;)m=m.o;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(k,l){var m=l&&typeof l;"object"==m||"function"==m?f.has(l)?m=f.get(l):(m=""+ ++h,f.set(l,m)):m="p_"+l;var p=k.b[m];if(p&&Ha(k.b,m))for(k=0;k<p.length;k++){var r=p[k];if(l!==l&&r.key!==r.key||l===r.key)return{id:m,list:p,index:k,l:r}}return{id:m,list:p,
index:-1,l:void 0}}function e(k){this.b={};this.a=b();this.size=0;if(k){k=ba(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(ba([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),p=m.next();if(p.done||p.value[0]!=k||"s"!=p.value[1])return!1;p=m.next();return p.done||4!=p.value[0].x||
"t"!=p.value[1]||!m.next().done?!1:!0}catch(r){return!1}}())return a;qa();var f=new WeakMap;e.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this.b[m.id]=[]);m.l?m.l.value=l:(m.l={next:this.a,o:this.a.o,head:this.a,key:k,value:l},m.list.push(m.l),this.a.o.next=m.l,this.a.o=m.l,this.size++);return this};e.prototype.delete=function(k){k=d(this,k);return k.l&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.b[k.id],k.l.o.next=k.l.next,k.l.next.o=k.l.o,k.l.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.o=b();this.size=0};e.prototype.has=function(k){return!!d(this,k).l};e.prototype.get=function(k){return(k=d(this,k).l)&&k.value};e.prototype.entries=function(){return c(this,function(k){return[k.key,k.value]})};e.prototype.keys=function(){return c(this,function(k){return k.key})};e.prototype.values=function(){return c(this,function(k){return k.value})};e.prototype.forEach=function(k,l){for(var m=this.entries(),p;!(p=m.next()).done;)p=
p.value,k.call(l,p[1],p[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var h=0;return e});var t=this||self;
function Ia(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function v(a){return"array"==Ia(a)}function Ja(a){var b=Ia(a);return"array"==b||"object"==b&&"number"==typeof a.length}function Ka(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var La=Date.now||function(){return+new Date};
function Ma(a,b){function c(){}c.prototype=b.prototype;a.Ea=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Na=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var Na;var Oa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Pa=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Qa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d},Ra=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};function Sa(a){return Array.prototype.concat.apply([],arguments)}
function Ta(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ua(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function Va(a){if(8192>=a.length)return String.fromCharCode.apply(null,a);for(var b="",c=0;c<a.length;c+=8192)b+=String.fromCharCode.apply(null,Ua(a,c,c+8192));return b};function Wa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var Xa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ya(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Xa.length;f++)c=Xa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Za(a,b){this.a=a===$a&&b||"";this.b=ab}g=Za.prototype;g.J=!0;g.H=function(){return this.a.toString()};g.M=!0;g.w=function(){return 1};g.Wa=function(a,b){var c=bb(this).toString();c=cb.exec(c);var d=c[3]||"";return new Za($a,c[1]+db("?",c[2]||"",a)+db("#",d,b))};function bb(a){if(a instanceof Za&&a.constructor===Za&&a.b===ab)return a.a;Ia(a);return"type_error:TrustedResourceUrl"}var cb=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,ab={};
function db(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=v(e)?e:[e];for(var f=0;f<e.length;f++){var h=e[f];null!=h&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(h)))}}return b}var $a={};var eb=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function fb(a,b){if(b)a=a.replace(gb,"&amp;").replace(hb,"&lt;").replace(ib,"&gt;").replace(jb,"&quot;").replace(kb,"&#39;").replace(lb,"&#0;");else{if(!mb.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(gb,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(hb,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ib,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(jb,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(kb,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(lb,"&#0;"))}return a}
var gb=/&/g,hb=/</g,ib=/>/g,jb=/"/g,kb=/'/g,lb=/\x00/g,mb=/[\x00&<>"']/;function w(a,b){return-1!=a.indexOf(b)}function nb(a,b){return a<b?-1:a>b?1:0};function x(a,b){this.a=a===ob&&b||"";this.b=pb}x.prototype.J=!0;x.prototype.H=function(){return this.a.toString()};x.prototype.M=!0;x.prototype.w=function(){return 1};function qb(a){if(a instanceof x&&a.constructor===x&&a.b===pb)return a.a;Ia(a);return"type_error:SafeUrl"}var pb={},ob={};var y;a:{var rb=t.navigator;if(rb){var sb=rb.userAgent;if(sb){y=sb;break a}}y=""};function z(){this.a="";this.c=tb;this.b=null}z.prototype.M=!0;z.prototype.w=function(){return this.b};z.prototype.J=!0;z.prototype.H=function(){return this.a.toString()};function ub(a){if(a instanceof z&&a.constructor===z&&a.c===tb)return a.a;Ia(a);return"type_error:SafeHtml"}function vb(a){if(a instanceof z)return a;var b="object"==typeof a,c=null;b&&a.M&&(c=a.w());return wb(fb(b&&a.J?a.H():String(a)),c)}
function xb(a){function b(f){v(f)?Pa(f,b):(f=vb(f),e.push(ub(f).toString()),f=f.w(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=vb(zb),d=c.w(),e=[];Pa(a,b);return wb(e.join(ub(c).toString()),d)}function Ab(a){return xb(Array.prototype.slice.call(arguments))}var tb={};function wb(a,b){return Bb(a,b)}function Bb(a,b){var c=new z;c.a=a;c.b=b;return c}Bb("<!DOCTYPE html>",0);var zb=Bb("",0),Cb=Bb("<br>",0);var Db=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=ub(zb);return!b.parentElement});function Eb(a,b){if(Db())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=ub(b)};function Fb(a){return a=fb(a,void 0)}var Gb=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};function A(a,b){a=String(a);var c=a.indexOf(".");-1==c&&(c=a.length);return Gb("0",Math.max(0,b-c))+a};function Hb(a,b){var c=Ib;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Jb=w(y,"Opera"),B=w(y,"Trident")||w(y,"MSIE"),Kb=w(y,"Edge"),Lb=w(y,"Gecko")&&!(w(y.toLowerCase(),"webkit")&&!w(y,"Edge"))&&!(w(y,"Trident")||w(y,"MSIE"))&&!w(y,"Edge"),Mb=w(y.toLowerCase(),"webkit")&&!w(y,"Edge");function Nb(){var a=t.document;return a?a.documentMode:void 0}var Ob;
a:{var Pb="",Qb=function(){var a=y;if(Lb)return/rv:([^\);]+)(\)|;)/.exec(a);if(Kb)return/Edge\/([\d\.]+)/.exec(a);if(B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Mb)return/WebKit\/(\S+)/.exec(a);if(Jb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Qb&&(Pb=Qb?Qb[1]:"");if(B){var Rb=Nb();if(null!=Rb&&Rb>parseFloat(Pb)){Ob=String(Rb);break a}}Ob=Pb}var Sb=Ob,Ib={};
function Tb(a){return Hb(a,function(){for(var b=0,c=eb(String(Sb)).split("."),d=eb(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=nb(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||nb(0==h[2].length,0==k[2].length)||nb(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var Ub;
Ub=t.document&&B?Nb():void 0;var Vb={},Wb=null;function Xb(a,b){void 0===b&&(b=0);Yb();b=Vb[b];for(var c=[],d=0;d<a.length;d+=3){var e=a[d],f=d+1<a.length,h=f?a[d+1]:0,k=d+2<a.length,l=k?a[d+2]:0,m=e>>2;e=(e&3)<<4|h>>4;h=(h&15)<<2|l>>6;l&=63;k||(l=64,f||(h=64));c.push(b[m],b[e],b[h]||"",b[l]||"")}return c.join("")}function Zb(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):w("=.",a[b-1])&&(c=w("=.",a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;$b(a,function(f){d[e++]=f});return d.subarray(0,e)}
function $b(a,b){function c(l){for(;d<a.length;){var m=a.charAt(d++),p=Wb[m];if(null!=p)return p;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return l}Yb();for(var d=0;;){var e=c(-1),f=c(0),h=c(64),k=c(64);if(64===k&&-1===e)break;b(e<<2|f>>4);64!=h&&(b(f<<4&240|h>>2),64!=k&&b(h<<6&192|k))}}
function Yb(){if(!Wb){Wb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));Vb[c]=d;for(var e=0;e<d.length;e++){var f=d[e];void 0===Wb[f]&&(Wb[f]=e)}}}};var C=0,D=0;function ac(a){var b=a>>>0;a=Math.floor((a-b)/4294967296)>>>0;C=b;D=a}function bc(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);a>>>=0;b&&(a=~a>>>0,c=(~c>>>0)+1,4294967295<c&&(c=0,a++,4294967295<a&&(a=0)));C=c;D=a}function cc(a){var b=0>a;a=2*Math.abs(a);ac(a);a=C;var c=D;b&&(0==a?0==c?c=a=4294967295:(c--,a=4294967295):a--);C=a;D=c}
function dc(a){var b=0>a?1:0;a=b?-a:a;if(0===a)0<1/a?C=D=0:(D=0,C=2147483648);else if(isNaN(a))D=0,C=2147483647;else if(3.4028234663852886E38<a)D=0,C=(b<<31|2139095040)>>>0;else if(1.1754943508222875E-38>a)a=Math.round(a/Math.pow(2,-149)),D=0,C=(b<<31|a)>>>0;else{var c=Math.floor(Math.log(a)/Math.LN2);a*=Math.pow(2,-c);a=Math.round(8388608*a)&8388607;D=0;C=(b<<31|c+127<<23|a)>>>0}}
function ec(a){var b=a.charCodeAt(4),c=a.charCodeAt(5),d=a.charCodeAt(6),e=a.charCodeAt(7);C=a.charCodeAt(0)+(a.charCodeAt(1)<<8)+(a.charCodeAt(2)<<16)+(a.charCodeAt(3)<<24)>>>0;D=b+(c<<8)+(d<<16)+(e<<24)>>>0}function fc(a,b,c){var d=b>>31;c(a<<1^d,(b<<1|a>>>31)^d)}
function gc(a){function b(h,k){for(var l=0;8>l&&(1!==h||0<k);l++)k=h*e[l]+k,e[l]=k&255,k>>>=8}function c(){for(var h=0;8>h;h++)e[h]=~e[h]&255}var d=!1;"-"===a[0]&&(d=!0,a=a.slice(1));for(var e=[0,0,0,0,0,0,0,0],f=0;f<a.length;f++)b(10,a.charCodeAt(f)-48);d&&(c(),b(1,1));return Va(e)};function E(a,b){this.a=a;this.b=b}function hc(a){return new E((a.a>>>1|(a.b&1)<<31)>>>0,a.b>>>1>>>0)}function ic(a){return new E(a.a<<1>>>0,(a.b<<1|a.a>>>31)>>>0)}g=E.prototype;g.ed=function(){return!!(this.a&1)};g.add=function(a){return new E((this.a+a.a&4294967295)>>>0>>>0,((this.b+a.b&4294967295)>>>0)+(4294967296<=this.a+a.a?1:0)>>>0)};g.sub=function(a){return new E((this.a-a.a&4294967295)>>>0>>>0,((this.b-a.b&4294967295)>>>0)-(0>this.a-a.a?1:0)>>>0)};
function jc(a){var b=a&65535,c=a>>>16;a=10*b+65536*(0*b&65535)+65536*(10*c&65535);for(b=0*c+(0*b>>>16)+(10*c>>>16);4294967296<=a;)a-=4294967296,b+=1;return new E(a>>>0,b>>>0)}g.toString=function(){for(var a="",b=this;0!=b.a||0!=b.b;){var c=new E(0,0);b=new E(b.a,b.b);for(var d=new E(10,0),e=new E(1,0);!(d.b&2147483648);)d=ic(d),e=ic(e);for(;0!=e.a||0!=e.b;)0>=(d.b<b.b||d.b==b.b&&d.a<b.a?-1:d.b==b.b&&d.a==b.a?0:1)&&(c=c.add(e),b=b.sub(d)),d=hc(d),e=hc(e);c=[c,b];b=c[0];a=c[1].a+a}""==a&&(a="0");return a};
function kc(a){for(var b=new E(0,0),c=new E(0,0),d=0;d<a.length;d++){if("0">a[d]||"9"<a[d])return null;c.a=parseInt(a[d],10);var e=jc(b.a);b=jc(b.b);b.b=b.a;b.a=0;b=e.add(b).add(c)}return b}g.ad=function(){return new E(this.a,this.b)};function lc(a,b){this.a=a;this.b=b}lc.prototype.add=function(a){return new lc((this.a+a.a&4294967295)>>>0>>>0,((this.b+a.b&4294967295)>>>0)+(4294967296<=this.a+a.a?1:0)>>>0)};
lc.prototype.sub=function(a){return new lc((this.a-a.a&4294967295)>>>0>>>0,((this.b-a.b&4294967295)>>>0)-(0>this.a-a.a?1:0)>>>0)};lc.prototype.c=function(){return new lc(this.a,this.b)};lc.prototype.toString=function(){var a=0!=(this.b&2147483648),b=new E(this.a,this.b);a&&(b=(new E(0,0)).sub(b));return(a?"-":"")+b.toString()};function mc(a){var b=0<a.length&&"-"==a[0];b&&(a=a.substring(1));a=kc(a);if(null===a)return null;b&&(a=(new E(0,0)).sub(a));return new lc(a.a,a.b)};function nc(){this.a=[]}g=nc.prototype;g.length=function(){return this.a.length};function oc(a){var b=a.a;a.a=[];return b}function F(a,b,c){for(;0<c||127<b;)a.a.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.a.push(b)}function G(a,b,c){I(a,b);I(a,c)}function J(a,b){for(;127<b;)a.a.push(b&127|128),b>>>=7;a.a.push(b)}function pc(a,b){if(0<=b)J(a,b);else{for(var c=0;9>c;c++)a.a.push(b&127|128),b>>=7;a.a.push(1)}}function qc(a,b){J(a,(b<<1^b>>31)>>>0)}
function rc(a,b){ec(b);fc(C,D,function(c,d){F(a,c>>>0,d>>>0)})}g.Af=function(a){this.a.push(a>>>0&255)};g.zf=function(a){this.a.push(a>>>0&255);this.a.push(a>>>8&255)};function I(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)}function sc(a,b){ac(b);I(a,C);I(a,D)}g.qe=function(a){this.a.push(a>>>0&255)};g.pe=function(a){this.a.push(a>>>0&255);this.a.push(a>>>8&255)};
function tc(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)}
function uc(a,b){var c=b;c=(b=0>c?1:0)?-c:c;if(0===c)D=0<1/c?0:2147483648,C=0;else if(isNaN(c))D=2147483647,C=4294967295;else if(1.7976931348623157E308<c)D=(b<<31|2146435072)>>>0,C=0;else if(2.2250738585072014E-308>c)c/=Math.pow(2,-1074),D=(b<<31|c/4294967296)>>>0,C=c>>>0;else{var d=c,e=0;if(2<=d)for(;2<=d&&1023>e;)e++,d/=2;else for(;1>d&&-1022<e;)d*=2,e--;c*=Math.pow(2,-e);D=(b<<31|e+1023<<20|1048576*c&1048575)>>>0;C=4503599627370496*c>>>0}I(a,C);I(a,D)}
g.Xc=function(a){this.a.push.apply(this.a,a)};function vc(a,b){ec(b);I(a,C);I(a,D)};function wc(){this.c=[];this.b=0;this.a=new nc;this.f=[]}function xc(a,b){var c=oc(a.a);a.c.push(c);a.c.push(b);a.b+=c.length+b.length}function K(a,b){L(a,b,2);b=oc(a.a);a.c.push(b);a.b+=b.length;b.push(a.b);return b}function M(a,b){var c=b.pop();for(c=a.b+a.a.length()-c;127<c;)b.push(c&127|128),c>>>=7,a.b++;b.push(c);a.b++}g=wc.prototype;g.hd=function(a,b,c){null!=a&&null!=b&&null!=c&&xc(this,a.subarray(b,c))};g.Yc=function(){this.c=[];oc(this.a);this.b=0;this.f=[]};
function yc(a){for(var b=new Uint8Array(a.b+a.a.length()),c=a.c,d=c.length,e=0,f=0;f<d;f++){var h=c[f];b.set(h,e);e+=h.length}c=oc(a.a);b.set(c,e);a.c=[b];return b}g.Yb=function(a){return Xb(yc(this),a)};g.Oa=function(a){this.f.push(K(this,a))};g.cb=function(){M(this,this.f.pop())};function L(a,b,c){J(a.a,8*b+c)}
g.ne=function(a,b,c){switch(a){case 1:null!=c&&(L(this,b,1),uc(this.a,c));break;case 2:null!=c&&(L(this,b,5),a=this.a,dc(c),I(a,C));break;case 3:null!=c&&zc(this,b,c);break;case 4:null!=c&&null!=c&&(L(this,b,0),a=this.a,bc(c),F(a,C,D));break;case 5:null!=c&&Ac(this,b,c);break;case 6:null!=c&&(L(this,b,1),sc(this.a,c));break;case 7:null!=c&&(L(this,b,5),I(this.a,c));break;case 8:Bc(this,b,c);break;case 9:N(this,b,c);break;case 12:Cc(this,b,c);break;case 13:null!=c&&Dc(this,b,c);break;case 14:Ec(this,
b,c);break;case 15:null!=c&&(L(this,b,5),tc(this.a,c));break;case 16:null!=c&&(L(this,b,1),a=this.a,bc(c),G(a,C,D));break;case 17:null!=c&&null!=c&&(L(this,b,0),qc(this.a,c));break;case 18:null!=c&&null!=c&&(L(this,b,0),a=this.a,cc(c),F(a,C,D));break;case 30:null!=c&&(L(this,b,1),vc(this.a,c));break;case 31:null!=c&&(L(this,b,0),a=this.a,ec(c),F(a,C,D))}};function Dc(a,b,c){null!=c&&(L(a,b,0),J(a.a,c))}function Ac(a,b,c){null!=c&&(L(a,b,0),pc(a.a,c))}
function zc(a,b,c){null!=c&&(L(a,b,0),a=a.a,bc(c),F(a,C,D))}g.yf=function(a,b){null!=b&&null!=b&&(L(this,a,0),rc(this.a,b))};g.xf=function(a,b){null!=b&&null!=b&&(L(this,a,0),rc(this.a,gc(b)))};function Bc(a,b,c){null!=c&&(L(a,b,0),a.a.a.push(c?1:0))}function Ec(a,b,c){null!=c&&(L(a,b,0),pc(a.a,c))}
function N(a,b,c){if(null!=c){b=K(a,b);for(var d=a.a,e=0;e<c.length;e++){var f=c.charCodeAt(e);if(128>f)d.a.push(f);else if(2048>f)d.a.push(f>>6|192),d.a.push(f&63|128);else if(65536>f)if(55296<=f&&56319>=f&&e+1<c.length){var h=c.charCodeAt(e+1);56320<=h&&57343>=h&&(f=1024*(f-55296)+h-56320+65536,d.a.push(f>>18|240),d.a.push(f>>12&63|128),d.a.push(f>>6&63|128),d.a.push(f&63|128),e++)}else d.a.push(f>>12|224),d.a.push(f>>6&63|128),d.a.push(f&63|128)}M(a,b)}}
function Cc(a,b,c){null!=c&&(c=c.constructor===Uint8Array?c:c.constructor===ArrayBuffer?new Uint8Array(c):c.constructor===Array?new Uint8Array(c):c.constructor===String?Zb(c):new Uint8Array(0),L(a,b,2),J(a.a,c.length),xc(a,c))}function Fc(a,b,c,d){null!=c&&(b=K(a,b),d(c,a),M(a,b))}g.re=function(a,b,c){null!=b&&(L(this,1,3),L(this,2,0),pc(this.a,a),a=K(this,3),c(b,this),M(this,a),L(this,1,4))};g.oe=function(a,b,c){null!=b&&(L(this,a,3),c(b,this),L(this,a,4))};
function Gc(a,b,c,d){L(a,b,0);var e=a.a;fc(c,d,function(f,h){F(e,f>>>0,h>>>0)})}g.cf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Ac(this,a,b[c])};g.df=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Ac(this,a,parseInt(d,10))}};g.ef=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)zc(this,a,b[c])};g.pf=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var f=c(b[e]),h=d(b[e]);L(this,a,1);G(this.a,f,h)}};
g.qf=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var f=c(b[e]),h=d(b[e]);L(this,a,0);F(this.a,f,h)}};g.rf=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++)Gc(this,a,c(b[e]),d(b[e]))};g.ff=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=mc(e),L(this,d,0),F(this.a,e.a,e.b))}};g.sf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Dc(this,a,b[c])};g.tf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Dc(this,a,parseInt(d,10))}};
g.uf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,0);var e=this.a;bc(d);F(e,C,D)}}};g.vf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=kc(e),L(this,d,0),F(this.a,e.a,e.b))}};g.kf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,0),qc(this.a,d))}};g.lf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,0);var e=this.a;cc(d);F(e,C,D)}}};
g.mf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,0),rc(this.a,gc(d)))}};g.nf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,0),rc(this.a,d))}};g.Xe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,5),I(this.a,d))}};g.Ye=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,1),sc(this.a,d))}};
g.Ze=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=kc(e),L(this,d,1),G(this.a,e.a,e.b))}};g.gf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,5),tc(this.a,d))}};g.hf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,1);var e=this.a;bc(d);G(e,C,D)}}};g.jf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=mc(e),L(this,d,1),G(this.a,e.a,e.b))}};
g.af=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,5);var e=this.a;dc(d);I(e,C)}}};g.Ve=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,1),uc(this.a,d))}};g.Te=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Bc(this,a,b[c])};g.We=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Ec(this,a,b[c])};g.Ue=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Cc(this,a,b[c])};
g.bf=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++)L(this,a,3),c(b[d],this),L(this,a,4)};g.$e=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,1),vc(this.a,d))}};g.wf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,0);var e=this.a;ec(d);F(e,C,D)}}};g.Ae=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++)pc(this.a,b[c]);M(this,a)}};
g.Be=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++)pc(this.a,parseInt(b[c],10));M(this,a)}};g.Ce=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++){var d=this.a;bc(b[c]);F(d,C,D)}M(this,a)}};g.Le=function(a,b,c,d){if(null!=b){a=K(this,a);for(var e=0;e<b.length;e++)G(this.a,c(b[e]),d(b[e]));M(this,a)}};g.Me=function(a,b,c,d){if(null!=b){a=K(this,a);for(var e=0;e<b.length;e++)F(this.a,c(b[e]),d(b[e]));M(this,a)}};
g.Ne=function(a,b,c,d){if(null!=b){a=K(this,a);for(var e=this.a,f=0;f<b.length;f++)fc(c(b[f]),d(b[f]),function(h,k){F(e,h>>>0,k>>>0)});M(this,a)}};g.De=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++){var d=mc(b[c]);F(this.a,d.a,d.b)}M(this,a)}};g.Oe=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++)J(this.a,b[c]);M(this,a)}};g.Pe=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++)J(this.a,parseInt(b[c],10));M(this,a)}};
g.Qe=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++){var d=this.a;bc(b[c]);F(d,C,D)}M(this,a)}};g.Re=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++){var d=kc(b[c]);F(this.a,d.a,d.b)}M(this,a)}};g.He=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++)qc(this.a,b[c]);M(this,a)}};g.Ie=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++){var d=this.a;cc(b[c]);F(d,C,D)}M(this,a)}};
g.Je=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++)rc(this.a,gc(b[c]));M(this,a)}};g.Ke=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++)rc(this.a,b[c]);M(this,a)}};g.ve=function(a,b){if(null!=b&&b.length)for(L(this,a,2),J(this.a,4*b.length),a=0;a<b.length;a++)I(this.a,b[a])};g.we=function(a,b){if(null!=b&&b.length)for(L(this,a,2),J(this.a,8*b.length),a=0;a<b.length;a++)sc(this.a,b[a])};
g.xe=function(a,b){if(null!=b&&b.length)for(L(this,a,2),J(this.a,8*b.length),a=0;a<b.length;a++){var c=kc(b[a]);G(this.a,c.a,c.b)}};g.Ee=function(a,b){if(null!=b&&b.length)for(L(this,a,2),J(this.a,4*b.length),a=0;a<b.length;a++)tc(this.a,b[a])};g.Fe=function(a,b){if(null!=b&&b.length)for(L(this,a,2),J(this.a,8*b.length),a=0;a<b.length;a++){var c=this.a;bc(b[a]);G(c,C,D)}};
g.Ge=function(a,b){if(null!=b&&b.length)for(L(this,a,2),J(this.a,8*b.length),a=0;a<b.length;a++){var c=this.a;ec(gc(b[a]));G(c,C,D)}};g.ze=function(a,b){if(null!=b&&b.length)for(L(this,a,2),J(this.a,4*b.length),a=0;a<b.length;a++){var c=this.a;dc(b[a]);I(c,C)}};g.te=function(a,b){if(null!=b&&b.length)for(L(this,a,2),J(this.a,8*b.length),a=0;a<b.length;a++)uc(this.a,b[a])};g.se=function(a,b){if(null!=b&&b.length)for(L(this,a,2),J(this.a,b.length),a=0;a<b.length;a++)this.a.a.push(b[a]?1:0)};
g.ue=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++)pc(this.a,b[c]);M(this,a)}};g.ye=function(a,b){if(null!=b&&b.length)for(L(this,a,2),J(this.a,8*b.length),a=0;a<b.length;a++)vc(this.a,b[a])};g.Se=function(a,b){if(null!=b&&b.length){a=K(this,a);for(var c=0;c<b.length;c++){var d=this.a;ec(b[c]);F(d,C,D)}M(this,a)}};function Hc(){}var Ic="function"==typeof Uint8Array;Hc.prototype.N=function(){return this.h};function Jc(a,b,c,d){a.a=null;b||(b=[]);a.h=void 0;a.f=-1;a.c=b;a:{if(b=a.c.length){--b;var e=a.c[b];if(!(null===e||"object"!=typeof e||v(e)||Ic&&e instanceof Uint8Array)){a.g=b-a.f;a.b=e;break a}}a.g=Number.MAX_VALUE}a.v={};if(c)for(b=0;b<c.length;b++)e=c[b],e<a.g?(e+=a.f,a.c[e]=a.c[e]||Kc):(Lc(a),a.b[e]=a.b[e]||Kc);if(d&&d.length)for(b=0;b<d.length;b++)Mc(a,d[b])}var Kc=[];
function Lc(a){var b=a.g+a.f;a.c[b]||(a.b=a.c[b]={})}function O(a,b){if(b<a.g){b+=a.f;var c=a.c[b];return c===Kc?a.c[b]=[]:c}if(a.b)return c=a.b[b],c===Kc?a.b[b]=[]:c}function P(a,b,c){a=O(a,b);return null==a?c:a}function Nc(a,b){a=O(a,b);a=null==a?a:!!a;return null==a?!1:a}function Oc(a,b,c){b<a.g?a.c[b+a.f]=c:(Lc(a),a.b[b]=c);return a}function Q(a,b,c){return R(a,b,c,"")}function R(a,b,c,d){c!==d?Oc(a,b,c):a.c[b+a.f]=null;return a}
function Pc(a,b,c){var d=Mc(a,Qc[0]);d&&d!==b&&void 0!==c&&(a.a&&d in a.a&&(a.a[d]=void 0),Oc(a,d,void 0));return Oc(a,b,c)}function Mc(a,b){for(var c,d,e=0;e<b.length;e++){var f=b[e],h=O(a,f);null!=h&&(c=f,d=h,Oc(a,f,void 0))}return c?(Oc(a,c,d),c):0}function S(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=O(a,c);d&&(a.a[c]=new b(d))}return a.a[c]}function Rc(a){Sc(a,Tc);var b=a.a[1];b==Kc&&(b=a.a[1]=[]);return b}
function Sc(a,b){a.a||(a.a={});if(!a.a[1]){for(var c=O(a,1),d=[],e=0;e<c.length;e++)d[e]=new b(c[e]);a.a[1]=d}}function Uc(a,b){a.a||(a.a={});a.a[b]=void 0;return Oc(a,b,void 0)}function Vc(a){if(a.a)for(var b in a.a){var c=a.a[b];if(v(c))for(var d=0;d<c.length;d++)c[d]&&T(c[d]);else c&&T(c)}}function T(a){Vc(a);return a.c}g=Hc.prototype;
g.Ca=Ic?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){return Xb(this)};try{return JSON.stringify(this.c&&T(this),Wc)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.c&&T(this),Wc)};function Wc(a,b){return"number"!==typeof b||!isNaN(b)&&Infinity!==b&&-Infinity!==b?b:String(b)}g.toString=function(){Vc(this);return this.c.toString()};
g.$c=function(a){if(this.b){this.a||(this.a={});var b=a.c;if(a.f){if(a.a())return this.a[b]||(this.a[b]=Ra(this.b[b]||[],function(c){return new a.b(c)})),this.a[b]}else if(a.a())return!this.a[b]&&this.b[b]&&(this.a[b]=new a.b(this.b[b])),this.a[b];return this.b[b]}};g.Od=function(a,b){this.a||(this.a={});Lc(this);var c=a.c;a.f?(b=b||[],a.a()?(this.a[c]=b,this.b[c]=Ra(b,function(d){return T(d)})):this.b[c]=b):a.a()?(this.a[c]=b,this.b[c]=b?T(b):b):this.b[c]=b;return this};g.Va=function(){return new this.constructor(Xc(T(this)))};
g.Zc=function(){return new this.constructor(Xc(T(this)))};function Xc(a){if(v(a)){for(var b=Array(a.length),c=0;c<a.length;c++){var d=a[c];null!=d&&(b[c]="object"==typeof d?Xc(d):d)}return b}if(Ic&&a instanceof Uint8Array)return new Uint8Array(a);b={};for(c in a)d=a[c],null!=d&&(b[c]="object"==typeof d?Xc(d):d);return b};function Yc(a){Jc(this,a,null,Qc)}Ma(Yc,Hc);var Qc=[[1,2]];g=Yc.prototype;g.vb=function(){return Mc(this,Qc[0])};g.rd=function(a){return Zc(a,this)};function Zc(a,b){var c={color:P(b,1,0),me:Nc(b,2)};a&&(c.B=b);return c}g.pd=function(){var a=new wc;$c(this,a);return yc(a)};function $c(a,b){var c=O(a,1);null!=c&&Ec(b,1,c);c=O(a,2);null!=c&&Bc(b,2,c)}g.od=function(){return P(this,1,0)};g.qd=function(a){return Pc(this,1,a)};g.nd=function(){return Pc(this,1,void 0)};
g.Fc=function(){return null!=O(this,1)};g.ac=function(){return Nc(this,2)};g.ie=function(a){return Pc(this,2,a)};g.Ua=function(){return Pc(this,2,void 0)};g.Kc=function(){return null!=O(this,2)};function ad(a){Jc(this,a,null,null)}Ma(ad,Hc);g=ad.prototype;g.td=function(a){var b={je:P(this,1,0),query:P(this,4,""),Oc:Nc(this,5),Ma:Nc(this,6),locale:P(this,7,0),$a:P(this,8,0),gd:P(this,9,0),md:P(this,10,""),gb:P(this,11,""),Ya:P(this,12,0)};a&&(b.B=this);return b};
g.sd=function(){var a=new wc;var b=P(this,1,0);0!==b&&Ec(a,1,b);b=P(this,4,"");0<b.length&&N(a,4,b);(b=Nc(this,5))&&Bc(a,5,b);(b=Nc(this,6))&&Bc(a,6,b);b=P(this,7,0);0!==b&&Ec(a,7,b);b=P(this,8,0);0!==b&&Ec(a,8,b);b=P(this,9,0);0!==b&&null!=b&&Ac(a,9,b);b=P(this,10,"");0<b.length&&N(a,10,b);b=P(this,11,"");0<b.length&&N(a,11,b);b=P(this,12,0);0!==b&&Ec(a,12,b);return yc(a)};g.ce=function(a){return R(this,1,a,0)};g.Ud=function(a){return R(this,7,a,0)};g.Kd=function(a){return R(this,8,a,0)};
g.Zd=function(a){return Q(this,10,a)};g.Qd=function(a){return Q(this,11,a)};g.Jd=function(a){return R(this,12,a,0)};function bd(a){Jc(this,a,null,null)}Ma(bd,Hc);g=bd.prototype;g.Ad=function(a){return cd(a,this)};function cd(a,b){var c,d={name:P(b,1,""),path:P(b,2,""),position:P(b,3,0),ob:(c=S(b,Yc,4))&&Zc(a,c),background:(c=S(b,Yc,5))&&Zc(a,c)};a&&(d.B=b);return d}g.xd=function(){var a=new wc;dd(this,a);return yc(a)};function dd(a,b){var c=P(a,1,"");0<c.length&&N(b,1,c);c=P(a,2,"");0<c.length&&N(b,2,c);c=P(a,3,0);0!==c&&Ec(b,3,c);c=S(a,Yc,4);null!=c&&Fc(b,4,c,$c);c=S(a,Yc,5);null!=c&&Fc(b,5,c,$c)}
g.Vd=function(a){return Q(this,1,a)};g.yd=function(a){return Q(this,2,a)};g.zd=function(a){return R(this,3,a,0)};g.Qa=function(){return Uc(this,4)};g.Gc=function(){return null!=O(this,4)};g.Pa=function(){return Uc(this,5)};g.Ec=function(){return null!=O(this,5)};function ed(a){Jc(this,a,null,null)}Ma(ed,Hc);ed.prototype.O=function(a){return fd(a,this)};function fd(a,b){var c={Hd:P(b,1,0),jd:P(b,2,0)};a&&(c.B=b);return c}ed.prototype.j=function(){var a=new wc;gd(this,a);return yc(a)};function gd(a,b){var c=P(a,1,0);0!==c&&null!=c&&zc(b,1,c);c=P(a,2,0);0!==c&&null!=c&&Ac(b,2,c)}ed.prototype.P=function(){var a=P(this,1,0),b=P(this,2,0);return new Date(1E3*a+b/1E6)};
ed.prototype.i=function(a){R(this,1,Math.floor(a.getTime()/1E3),0);R(this,2,1E6*a.getMilliseconds(),0)};function Tc(a){Jc(this,a,hd,null)}Ma(Tc,Hc);var hd=[11];g=Tc.prototype;g.wd=function(a){return id(a,this)};function id(a,b){var c,d={title:P(b,1,""),type:P(b,2,""),ab:P(b,3,""),image:P(b,4,""),summary:P(b,5,""),timestamp:(c=S(b,ed,6))&&fd(a,c),url:P(b,7,""),ld:P(b,8,""),Ka:P(b,9,""),origin:P(b,10,""),cd:null==(c=O(b,11))?void 0:c,fb:P(b,12,""),icon:(c=S(b,bd,13))&&cd(a,c),color:P(b,14,""),ke:P(b,15,""),bb:P(b,16,0)};a&&(d.B=b);return d}g.ud=function(){var a=new wc;jd(this,a);return yc(a)};
function jd(a,b){var c=P(a,1,"");0<c.length&&N(b,1,c);c=P(a,2,"");0<c.length&&N(b,2,c);c=P(a,3,"");0<c.length&&N(b,3,c);c=P(a,4,"");0<c.length&&N(b,4,c);c=P(a,5,"");0<c.length&&N(b,5,c);c=S(a,ed,6);null!=c&&Fc(b,6,c,gd);c=P(a,7,"");0<c.length&&N(b,7,c);c=P(a,8,"");0<c.length&&N(b,8,c);c=P(a,9,"");0<c.length&&N(b,9,c);c=P(a,10,"");0<c.length&&N(b,10,c);c=O(a,11);if(0<c.length&&null!=c)for(var d=0;d<c.length;d++)N(b,11,c[d]);c=P(a,12,"");0<c.length&&N(b,12,c);c=S(a,bd,13);null!=c&&Fc(b,13,c,dd);c=P(a,
14,"");0<c.length&&N(b,14,c);c=P(a,15,"");0<c.length&&N(b,15,c);c=P(a,16,0);0!==c&&null!=c&&zc(b,16,c)}g.fe=function(a){return Q(this,1,a)};g.ge=function(a){return Q(this,2,a)};g.Ld=function(a){return Q(this,3,a)};g.Td=function(a){return Q(this,4,a)};g.be=function(a){return Q(this,5,a)};g.Ta=function(){return Uc(this,6)};g.Jc=function(){return null!=O(this,6)};g.he=function(a){return Q(this,7,a)};g.Yd=function(a){return Q(this,8,a)};g.Id=function(a){return Q(this,9,a)};
g.Wd=function(a){return Q(this,10,a)};g.La=function(a,b){var c=O(this,11);void 0!=b?c.splice(b,0,a):c.push(a);return this};g.Sa=function(){return Oc(this,11,[])};g.Pd=function(a){return Q(this,12,a)};g.Ra=function(){return Uc(this,13)};g.Hc=function(){return null!=O(this,13)};g.vd=function(a){return Q(this,14,a)};g.de=function(a){return Q(this,15,a)};g.Nd=function(a){return R(this,16,a,0)};function kd(a){Jc(this,a,ld,null)}Ma(kd,Hc);var ld=[1];kd.prototype.P=function(a){for(var b=Rc(this),c=id,d=[],e=0;e<b.length;e++)d[e]=c.call(b[e],a,b[e]);b={A:d};a&&(b.B=this);return b};kd.prototype.O=function(){var a=new wc;var b=Rc(this);if(0<b.length){var c=jd;if(null!=b)for(var d=0;d<b.length;d++){var e=K(a,1);c(b[d],a);M(a,e)}}return yc(a)};
kd.prototype.i=function(a,b){var c=Tc;Sc(this,c);var d=this.a[1];d||(d=this.a[1]=[]);a=a?a:new c;c=O(this,1);void 0!=b?(d.splice(b,0,a),c.splice(b,0,T(a))):(d.push(a),c.push(T(a)));return a};kd.prototype.j=function(){var a=[];this.a||(this.a={});a=a||[];for(var b=[],c=0;c<a.length;c++)b[c]=T(a[c]);this.a[1]=a;return Oc(this,1,b)};var md="StopIteration"in t?t.StopIteration:{message:"StopIteration",stack:""};function nd(){}nd.prototype.next=function(){throw md;};nd.prototype.a=function(){return this};function od(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof od)for(c=a.s(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}g=od.prototype;g.m=function(){pd(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};g.s=function(){pd(this);return this.a.concat()};
g.Ac=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(qd(this.b,c)&&this.b[c]==a)return!0}return!1};g.Bc=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||rd;pd(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function rd(a,b){return a===b}g.Cc=function(){return 0==this.c};g.zc=function(){this.b={};this.f=this.c=this.a.length=0};
function pd(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];qd(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],qd(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}g.get=function(a,b){return qd(this.b,a)?this.b[a]:b};g.set=function(a,b){qd(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};g.forEach=function(a,b){for(var c=this.s(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
g.le=function(){for(var a=new od,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};g.Dc=function(){pd(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};g.Ib=function(){return sd(this,!0)};g.bc=function(){return sd(this,!1)};function sd(a,b){pd(a);var c=0,d=a.f,e=new nd;e.next=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw md;var f=a.a[c++];return b?f:a.b[f]};return e}
function qd(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function td(a){if(a.m&&"function"==typeof a.m)return a.m();if("string"===typeof a)return a.split("");if(Ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function ud(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(Ja(a)||"string"===typeof a)Pa(a,b,c);else{if(a.s&&"function"==typeof a.s)var d=a.s();else if(a.m&&"function"==typeof a.m)d=void 0;else if(Ja(a)||"string"===typeof a){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else for(f in d=[],e=0,a)d[e++]=f;e=td(a);f=e.length;for(var h=0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};var vd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/\\#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function wd(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function xd(a){this.b=this.j=this.h="";this.f=null;this.i=this.c="";this.g=this.v=!1;if(a instanceof xd){this.g=a.g;yd(this,a.h);var b=a.j;U(this);this.j=b;b=a.b;U(this);this.b=b;zd(this,a.f);b=a.c;U(this);this.c=b;Ad(this,Bd(a.a));a=a.i;U(this);this.i=a}else a&&(b=String(a).match(vd))?(this.g=!1,yd(this,b[1]||"",!0),a=b[2]||"",U(this),this.j=Cd(a),a=b[3]||"",U(this),this.b=Cd(a,!0),zd(this,b[4]),a=b[5]||"",U(this),this.c=Cd(a,!0),Ad(this,b[6]||"",!0),a=b[7]||"",U(this),this.i=Cd(a)):(this.g=!1,this.a=
new Dd(null,this.g))}g=xd.prototype;g.toString=function(){var a=[],b=this.h;b&&a.push(Ed(b,Fd,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(Ed(b,Fd,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Ed(c,"/"==c.charAt(0)?Gd:Hd,!0));(c=this.a.toString())&&a.push("?",c);(c=this.i)&&a.push("#",Ed(c,Id));return a.join("")};
g.resolve=function(a){var b=new xd(this),c=!!a.h;c?yd(b,a.h):c=!!a.j;if(c){var d=a.j;U(b);b.j=d}else c=!!a.b;c?(d=a.b,U(b),b.b=d):c=null!=a.f;d=a.c;if(c)zd(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(w(e,"./")||w(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],h=0;h<e.length;){var k=e[h++];"."==k?d&&h==e.length&&f.push(""):".."==k?((1<f.length||1==f.length&&
""!=f[0])&&f.pop(),d&&h==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?(U(b),b.c=d):c=""!==a.a.toString();c?Ad(b,Bd(a.a)):c=!!a.i;c&&(a=a.i,U(b),b.i=a);return b};function yd(a,b,c){U(a);a.h=c?Cd(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))}function zd(a,b){U(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function Ad(a,b,c){U(a);b instanceof Dd?(a.a=b,Jd(a.a,a.g)):(c||(b=Ed(b,Kd)),a.a=new Dd(b,a.g));return a}
g.kc=function(a,b){return Ad(this,a,b)};g.wb=function(){return Cd(this.a.toString())};g.Xd=function(a,b){U(this);v(b)||(b=[String(b)]);Ld(this.a,a,b);return this};g.Sb=function(a){return this.a.m(a)};g.Ic=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};g.fd=function(){U(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^La()).toString(36);U(this);this.a.set("zx",a);return this};
g.ic=function(a){U(this);Md(this.a,a);return this};g.ae=function(a){this.v=a;return this};g.Vc=function(){return this.v};function U(a){if(a.v)throw Error("Tried to modify a read-only Uri");}g.jc=function(a){this.g=a;this.a&&Jd(this.a,a);return this};function Cd(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Ed(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Nd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}
function Nd(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Fd=/[#\/\?@]/g,Hd=/[#\?:]/g,Gd=/[#\?]/g,Kd=/[#\?@]/g,Id=/#/g;function Dd(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}function V(a){a.a||(a.a=new od,a.b=0,a.c&&wd(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}g=Dd.prototype;g.gc=function(){V(this);return this.b};g.add=function(a,b){V(this);this.c=null;a=Od(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
function Md(a,b){V(a);b=Od(a,b);qd(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,qd(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&pd(a)))}g.dc=function(){this.a=this.c=null;this.b=0};g.hc=function(){V(this);return 0==this.b};function Pd(a,b){V(a);b=Od(a,b);return qd(a.a.b,b)}g.ec=function(a){var b=this.m();return 0<=Oa(b,a)};g.forEach=function(a,b){V(this);this.a.forEach(function(c,d){Pa(c,function(e){a.call(b,e,d,this)},this)},this)};
g.s=function(){V(this);for(var a=this.a.m(),b=this.a.s(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};g.m=function(a){V(this);var b=[];if("string"===typeof a)Pd(this,a)&&(b=Sa(b,this.a.get(Od(this,a))));else{a=this.a.m();for(var c=0;c<a.length;c++)b=Sa(b,a[c])}return b};g.set=function(a,b){V(this);this.c=null;a=Od(this,a);Pd(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
g.get=function(a,b){if(!a)return b;a=this.m(a);return 0<a.length?String(a[0]):b};function Ld(a,b,c){Md(a,b);0<c.length&&(a.c=null,a.a.set(Od(a,b),Ta(c)),a.b+=c.length)}g.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.s(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.m(d);for(var f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}}return this.c=a.join("&")};
g.hb=function(a){V(this);this.a.forEach(function(b,c){0<=Oa(a,c)||Md(this,c)},this);return this};function Bd(a){var b=new Dd;b.c=a.c;a.a&&(b.a=new od(a.a),b.b=a.b);return b}function Od(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function Jd(a,b){b&&!a.f&&(V(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Md(this,d),Ld(this,e,c))},a));a.f=b}g.fc=function(a){for(var b=0;b<arguments.length;b++)ud(arguments[b],function(c,d){this.add(d,c)},this)};var Qd={},Rd={},Sd={},Td={};function Ud(){throw Error("Do not instantiate directly");}Ud.prototype.L=null;Ud.prototype.toString=function(){return this.I};Ud.prototype.a=function(){if(this.u!==Rd)throw Error("Sanitized content was not of kind URI.");return new x(ob,this.toString())};function Vd(){Ud.call(this)}Ma(Vd,Ud);Vd.prototype.u=Qd;function Wd(a,b){return null!=a&&a.u===b};function Xd(a){if(null!=a)switch(a.L){case 1:return 1;case -1:return-1;case 0:return 0}return null}function W(a){return Wd(a,Qd)?a:a instanceof z?Yd(ub(a).toString(),a.w()):Yd(Fb(String(String(a))),Xd(a))}var Yd=function(a){function b(c){this.I=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.L=d);return c}}(Vd);
function Zd(a,b){return a&&b&&a.Aa&&b.Aa?a.u!==b.u?!1:a.toString()===b.toString():a instanceof Ud&&b instanceof Ud?a.u!=b.u?!1:a.toString()==b.toString():a==b}function X(a){return Wd(a,Qd)?String(String(a.I).replace($d,"").replace(ae,"&lt;")).replace(be,ce):Fb(String(a))}function de(a){Wd(a,Td)?a=a.I.replace(/([^"'\s])$/,"$1 "):(a=String(a),a=ee.test(a)?a:"zSoyz");return a}
function fe(a){Wd(a,Rd)||Wd(a,Sd)?a=ge(a):a instanceof x?a=ge(qb(a)):a instanceof Za?a=ge(bb(a).toString()):(a=String(a),a=he.test(a)?a.replace(ie,je):"about:invalid#zSoyz");return a}function ke(a){return Ra(a,function(b){return"A"<=b&&"Z">=b?b.toLowerCase():b}).join("")}
var le={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function ce(a){return le[a]}
var me={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",
")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB",
"\uff3d":"%EF%BC%BD"};function je(a){return me[a]}
var be=/[\x00\x22\x27\x3c\x3e]/g,ne=/[\x00\x09-\x0d \x22\x26\x27\x2d\/\x3c-\x3e`\x85\xa0\u2028\u2029]/g,oe=/[\x00\x09-\x0d \x22\x27\x2d\/\x3c-\x3e`\x85\xa0\u2028\u2029]/g,ie=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,he=/^(?![^#?]*\/(?:\.|%2E){2}(?:[\/?#]|$))(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i,pe=/^[^&:\/?#]*(?:[\/?#]|$)|^https?:|^data:image\/[a-z0-9+]+;base64,[a-z0-9+\/]+=*$|^blob:/i,ee=
/^(?!on|src|(?:action|archive|background|cite|classid|codebase|content|data|dsync|href|http-equiv|longdesc|style|usemap)\s*$)(?:[a-z0-9_$:-]*)$/i;function ge(a){return String(a).replace(ie,je)}var $d=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,ae=/</g;function qe(a){v(a.A);var b=a.A;var c=a.C,d=a.D,e=a.X,f=a.Da,h=a.Z,k=a.$,l=a.Ba;a=a.va;var m='<devsite-sort sort-elements=".devsite-card-wrapper"'+(h?' sort-attribute="'+X(h)+'"':"")+(k?" sort-descending":"")+' ancestor="devsite-dynamic-content"><div class="devsite-card-group"'+(e?' dynamic-card-style="'+X(e)+'"':"")+">";if(b&&0<b.length)for(h=Math.max(0,Math.ceil(b.length)),k=0;k<h;k++){var p=k,r=b[p];m+='<div class="devsite-card-wrapper"';for(var H=Array.from(r.keys()),u=H.length,na=0;na<u;na++){var ya=
H[na];m+=" "+de(ya)+'="'+X(r.get(ya))+'"'}if(Zd(l,"button")||Zd(l,"both")){var yb;Zd(a,"")?r.get("displayOrigin")?yb=W(r.get("displayOrigin")):yb="More":yb=W(a);H='<div class="devsite-card-buttons"><a href="'+X(fe(r.get("url")))+'" class="button" data-category="Site-Wide Custom Events" data-label="devsite-dynamic-content card link" data-action="click">'+yb+"</a></div>"}else H="";p=(p>c-1?" hidden":"")+'><div class="devsite-card"'+(r.get("origin")?' dynamic-card-type="'+X(ke(""+r.get("origin")))+'"':
"");r.get("timestamp")?(u=r.get("timestamp"),u=" dynamic-card-timestamp="+(Wd(u,Qd)?String(String(u.I).replace($d,"").replace(ae,"&lt;")).replace(oe,ce):String(u).replace(ne,ce))):u="";p=p+u+'><a href="'+X(fe(r.get("url")))+'" class="devsite-card-image-bg '+(r.get("image")?"":"devsite-card-img-bg-default")+'" data-category="Site-Wide Custom Events" data-label="devsite-dynamic-content card link" data-action="click"';r.get("image")?(u=r.get("image"),Wd(u,Rd)||Wd(u,Sd)?u=ge(u):u instanceof x?u=ge(qb(u)):
u instanceof Za?u=ge(bb(u).toString()):(u=String(u),u=pe.test(u)?u.replace(ie,je):"about:invalid#zSoyz"),u=' style="background-image: url('+X(u)+');"'):u="";m+=p+u+"></a>"+(f&&r.get("account")?'<div class="devsite-card-content-wrapper">':"")+'<div class="devsite-card-content">'+(r.get("displayOrigin")?'<p class="devsite-card-category">'+W(r.get("displayOrigin"))+"</p>":"")+(r.get("displayTitle")?(Zd(l,"heading")||Zd(l,"both")?'<a href="'+X(fe(r.get("url")))+'" data-category="Site-Wide Custom Events" data-label="devsite-dynamic-content card link" data-action="click">':
"")+'<h3 class="no-link hide-from-toc">'+W(r.get("displayTitle"))+"</h3>"+(Zd(l,"heading")||Zd(l,"both")?"</a>":""):"")+(!Zd(e,"small")&&r.get("summary")?'<p class="devsite-card-summary">'+W(r.get("summary"))+"</p>":"")+"</div>"+(f&&r.get("account")?'<div class="devsite-card-author"><p class="devsite-card-author-name">'+W(r.get("account"))+"</p>"+(r.get("formattedTimestamp")?'<p class="devsite-card-author-date">'+W(r.get("formattedTimestamp"))+"</p>":"")+"</div>":"")+H+(f&&r.get("account")?"</div>":
"")+"</div></div>"}m+="</div></devsite-sort>"+(b.length>c?re({C:c,D:d}):"");return Yd(m)}
function se(a){v(a.A);var b=a.A;var c=a.C,d=a.D,e=a.Z;a=a.$;e='<devsite-sort sort-elements=".devsite-card-list-item"'+(e?' sort-attribute="'+X(e)+'"':"")+(a?" sort-descending":"")+' ancestor="devsite-dynamic-content"><ul class="devsite-card-list">';a=Math.max(0,Math.ceil(b.length));for(var f=0;f<a;f++){var h=f,k=b[h];e+='<li class="devsite-card-list-item"';for(var l=Array.from(k.keys()),m=l.length,p=0;p<m;p++){var r=l[p];e+=" "+de(r)+'="'+X(k.get(r))+'"'}e+=(h>c-1?" hidden":"")+'><a class="devsite-card-list-link" href="'+
X(fe(k.get("url")))+'" data-category="Site-Wide Custom Events" data-label="devsite-dynamic-content list link" data-action="click">'+W(k.get("displayTitle"))+"</a></li>"}e+="</ul></devsite-sort>"+(b.length>c?re({C:c,D:d}):"");return Yd(e)}function re(a){var b=a.C;return Yd('<devsite-pagination elements=".devsite-card-wrapper" container="devsite-dynamic-content" elements-per-page="'+X(a.D)+'" initial-results="'+X(b)+'" buttons></devsite-pagination>')}
function te(a){return Yd('<aside class="devsite-dynamic-content-message caution">'+W(a.message)+"</aside>")};var ue=!B||9<=Number(Ub),ve=!Lb&&!B||B&&9<=Number(Ub)||Lb&&Tb("1.9.1"),we=B&&!Tb("9"),xe=B||Jb||Mb;function ye(a,b){this.x=void 0!==a?a:0;this.a=void 0!==b?b:0}g=ye.prototype;g.tc=function(){return new ye(this.x,this.a)};g.uc=function(a){return a instanceof ye&&(this==a?!0:this&&a?this.x==a.x&&this.a==a.a:!1)};g.ceil=function(){this.x=Math.ceil(this.x);this.a=Math.ceil(this.a);return this};g.floor=function(){this.x=Math.floor(this.x);this.a=Math.floor(this.a);return this};g.round=function(){this.x=Math.round(this.x);this.a=Math.round(this.a);return this};
g.wc=function(a,b){a instanceof ye?(this.x+=a.x,this.a+=a.a):(this.x+=Number(a),"number"===typeof b&&(this.a+=b));return this};g.vc=function(a,b){this.x*=a;this.a*="number"===typeof b?b:a;return this};g.Dd=function(a,b){a=a*Math.PI/180;b=b||new ye(0,0);var c=this.x,d=this.a,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.a)*a+b.x;this.a=(c-b.x)*a+(d-b.a)*e+b.a};function ze(a,b){this.width=a;this.height=b}g=ze.prototype;g.xc=function(){return new ze(this.width,this.height)};g.Kb=function(){return Math.max(this.width,this.height)};g.Zb=function(){return Math.min(this.width,this.height)};g.kd=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.yc=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.lb=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Ae(a,b){a.width*=b;a.height*=b;return a}g.Fd=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Ae(this,a)};
g.Gd=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Ae(this,a)};function Be(a){return a?new Ce(De(a)):Na||(Na=new Ce)}function Ee(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Fe(document,"*",a,b);return d||null}
function Ge(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var k;if(k="function"==typeof e.split)k=0<=Oa(e.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function Fe(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Ge(a,b,c,d)[0]||null}function He(a,b){Wa(b,function(c,d){c&&"object"==typeof c&&c.J&&(c=c.H());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Ie.hasOwnProperty(d)?a.setAttribute(Ie[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Ie={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Je(a){a=a.document;a=Ke(a)?a.documentElement:a.body;return new ze(a.clientWidth,a.clientHeight)}function Le(a){return a.scrollingElement?a.scrollingElement:!Mb&&Ke(a)?a.documentElement:a.body||a.documentElement}
function Me(a){return a.parentWindow||a.defaultView}function Ne(a,b,c,d){function e(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];Ja(f)&&!Oe(f)?Pa(Pe(f)?Ta(f):f,e):e(f)}}function Qe(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function Ke(a){return"CSS1Compat"==a.compatMode}function Re(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function Se(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function Te(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function Oe(a){return Ka(a)&&0<a.nodeType}function Ue(a){return Ka(a)&&1==a.nodeType}function Ve(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function We(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return Xe(b,a)}function Xe(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function De(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Ye(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else Re(a),a.appendChild(De(a).createTextNode(String(b)))}function Ze(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||Ze(a,b,c,d))return!0;a=a.nextSibling}return!1}var $e={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},af={IMG:" ",BR:"\n"};
function bf(a){return cf(a)&&df(a)}function cf(a){return B&&!Tb("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function df(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function ef(a){if(we&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];ff(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");we||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function ff(a,b,c){if(!(a.nodeName in $e))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in af)b.push(af[a.nodeName]);else for(a=a.firstChild;a;)ff(a,b,c),a=a.nextSibling}function Pe(a){if(a&&"number"==typeof a.length){if(Ka(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==Ia(a))return"function"==typeof a.item}return!1}
function gf(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return hf(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h="string"===typeof f.className)&&(h=0<=Oa(f.className.split(/\s+/),c));return h},!0,d)}function hf(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function Ce(a){this.a=a||t.document||document}g=Ce.prototype;g.Bb=Be;g.Md=function(a){this.a=a};g.xb=function(){return this.a};
g.ya=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Wb=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Fa=Ce.prototype.ya;g.qc=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.za=function(a,b,c){return Ge(this.a,a,b,c)};g.Db=function(a,b,c){return Fe(this.a,a,b,c)};g.Eb=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Ge(document,"*",a,b)};g.Cb=function(a,b){return Ee(a,b||this.a)};
g.Xb=function(a,b){return Ee(a,b||this.a)};g.Ga=Ce.prototype.za;g.$d=He;g.cc=function(a){return Je(a||Me(this.a)||window)};g.yb=function(){var a=Me(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Je(a).height,Ke(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.wa=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!ue&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',Fb(h.name),'"');if(h.type){f.push(' type="',Fb(h.type),'"');var k={};Ya(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=Qe(d,f);h&&("string"===typeof h?f.className=h:v(h)?f.className=h.join(" "):He(f,h));2<e.length&&Ne(d,f,e,2);return f};g.Ha=Ce.prototype.wa;g.pc=function(a){return this.a.createTextNode(String(a))};
g.Za=function(a,b,c){var d=this.a;c=!!c;for(var e=Qe(d,"TABLE"),f=e.appendChild(Qe(d,"TBODY")),h=0;h<a;h++){for(var k=Qe(d,"TR"),l=0;l<b;l++){var m=Qe(d,"TD");c&&Ye(m,"\u00a0");k.appendChild(m)}f.appendChild(k)}return e};g.Ed=function(a){var b=this.a;var c=Qe(b,"DIV");B?(a=Ab(Cb,a),Eb(c,a),c.removeChild(c.firstChild)):Eb(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.Pc=function(){return Ke(this.a)};
g.Ab=function(){return Le(this.a)};g.zb=function(){var a=this.a,b=Le(a);a=Me(a);return B&&Tb("10")&&a.pageYOffset!=b.scrollTop?new ye(b.scrollLeft,b.scrollTop):new ye(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.pb=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.mc=function(a,b){a.appendChild(b)};g.lc=function(a,b){Ne(De(a),a,arguments,1)};g.nc=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.Cd=Re;g.Nc=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.Mc=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.Lc=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.rc=Se;g.sc=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.mb=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return Se(a)}};
g.ub=function(a){return ve&&void 0!=a.children?a.children:Qa(a.childNodes,function(b){return 1==b.nodeType})};g.Fb=function(a){return void 0!==a.firstElementChild?a.firstElementChild:Te(a.firstChild,!0)};g.Jb=function(a){return void 0!==a.lastElementChild?a.lastElementChild:Te(a.lastChild,!1)};g.Lb=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:Te(a.nextSibling,!0)};g.Ub=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:Te(a.previousSibling,!1)};
g.Mb=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Vb=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.Tc=Oe;g.Qc=Ue;g.Wc=function(a){return Ka(a)&&a.window==a};g.Tb=function(a){var b;if(xe&&!(B&&Tb("9")&&!Tb("10")&&t.SVGElement&&a instanceof t.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return Ue(b)?b:null};
g.oc=Ve;
g.Xa=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(B&&!(9<=Number(Ub))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Xe(a,b):!c&&Ve(e,b)?-1*We(a,b):!d&&Ve(f,a)?We(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=De(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(t.Range.START_TO_END,a)};g.ib=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.Rb=De;g.Gb=function(a){return a.contentDocument||a.contentWindow.document};
g.Hb=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?Me(c):window}else d=null;b=d}return b}catch(e){}return null};g.ee=Ye;g.Qb=function(a){if("outerHTML"in a)return a.outerHTML;var b=Qe(De(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.jb=function(a,b){var c=[];return Ze(a,b,c,!0)?c[0]:void 0};g.kb=function(a,b){var c=[];Ze(a,b,c,!1);return c};g.Sc=bf;g.Sd=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.Rc=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!cf(a)||df(a)):bf(a))&&B){var c;"function"!=Ia(a.getBoundingClientRect)||B&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.$b=ef;g.Ob=function(a){return ef(a).length};
g.Pb=function(a,b){b=b||De(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(ef(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Nb=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in $e))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in af)d+=af[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);Ka(c)&&(c.Bd=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.Uc=Pe;g.sb=gf;g.rb=function(a,b,c){return gf(a,null,b,c)};g.qb=hf;g.tb=function(a){return a.getContext("2d")};function jf(a,b){b=void 0===b?null:b;var c=void 0===c?"POST":c;var d=void 0===d?!1:d;var e=new Headers;e.append("X-Requested-With","XMLHttpRequest");if("POST"===c||d)d=document.querySelector('meta[name~="xsrf_token"]'),null!==d&&e.append("X-XSRF-TOKEN",d.getAttribute("content"));"/"===a[0]&&(a=a.substring(1));a=kf("/_d/"+a);return window.fetch(a.href,{method:c,headers:e,body:b,credentials:"include"}).then(function(f){return f.ok?Promise.resolve(f):Promise.reject(f)}).then(function(f){var h=f.headers.get("Content-Type");
return h&&-1!==h.indexOf("application/json")?f.text():Promise.reject(f)}).then(function(f){return Promise.resolve(f.replace(")]}'\n",""))})}function kf(a){var b=new URL(document.location.toString());a=new URL(a,b.origin);if(a.hostname!==b.hostname)return a;var c=new xd(b.href),d=new xd(a.href);"tenant hl authuser acting_user mv mh skip_cache".split(" ").forEach(function(e){var f=c.a.get(e);f&&!d.a.get(e)&&(U(d),d.a.set(e,f))});a.search=d.a.toString();return a};var lf=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(lf&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function mf(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ja(mf,HTMLElement);mf.prototype.N=function(){console.warn(this.tagName,"has not implemented update")};mf.prototype.j=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
mf.prototype.v=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};var nf={fa:["BC","AD"],ea:["Before Christ","Anno Domini"],ha:"JFMAMJJASOND".split(""),na:"JFMAMJJASOND".split(""),ga:"January February March April May June July August September October November December".split(" "),ma:"January February March April May June July August September October November December".split(" "),ja:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),pa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),sa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
ra:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),la:"Sun Mon Tue Wed Thu Fri Sat".split(" "),qa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),Ia:"SMTWTFS".split(""),oa:"SMTWTFS".split(""),ka:["Q1","Q2","Q3","Q4"],ia:["1st quarter","2nd quarter","3rd quarter","4th quarter"],aa:["AM","PM"],R:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],W:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],ba:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],S:6,Ja:[5,6],T:5},of=nf;
of=nf;function pf(a,b,c,d,e){a=new Date(a,b,c);e=e||0;return a.valueOf()+864E5*(((void 0!==d?d:3)-e+7)%7-((a.getDay()+6)%7-e+7)%7)};function qf(){}function rf(a){if("number"==typeof a){var b=new qf;b.b=a;var c=a;if(0==c)c="Etc/GMT";else{var d=["Etc/GMT",0>c?"-":"+"];c=Math.abs(c);d.push(Math.floor(c/60)%100);c%=60;0!=c&&d.push(":",A(c,2));c=d.join("")}b.f=c;c=sf(a);a=tf(a);b.g=[c,c];b.a={V:a,U:a};b.c=[];return b}b=new qf;b.f=a.id;b.b=-a.std_offset;b.g=a.names;b.a=a.names_ext;b.c=a.transitions;return b}
function tf(a){var b=["GMT"];b.push(0>=a?"+":"-");a=Math.abs(a);b.push(A(Math.floor(a/60)%100,2),":",A(a%60,2));return b.join("")}function sf(a){if(0==a)return"UTC";var b=["UTC",0>a?"+":"-"];a=Math.abs(a);b.push(Math.floor(a/60)%100);a%=60;0!=a&&b.push(":",a);return b.join("")}qf.prototype.i=function(){var a=this.f,b=-this.b,c=Ta(this.g),d=this.a,e={},f;for(f in d)e[f]=d[f];return{id:a,std_offset:b,names:c,names_ext:e,transitions:Ta(this.c)}};
function uf(a,b){b=Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate(),b.getUTCHours(),b.getUTCMinutes())/36E5;for(var c=0;c<a.c.length&&b>=a.c[c];)c+=2;return 0==c?0:a.c[c-1]}qf.prototype.j=function(a){return sf(this.b-uf(this,a))};qf.prototype.h=function(a){return 0<uf(this,a)?void 0!==this.a.da?this.a.da:this.a.DST_LONG_NAME_GMT:void 0!==this.a.V?this.a.V:this.a.STD_LONG_NAME_GMT};function vf(){this.b=[];this.a=of;wf(this,1)}var xf=[/^'(?:[^']|'')*('|$)/,/^(?:G+|y+|Y+|M+|k+|S+|E+|a+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|V+|w+|z+|Z+)/,/^[^'GyYMkSEahKHcLQdmsvVwzZ]+/];function yf(a){return a.getHours?a.getHours():0}function zf(a,b){if(!b)throw Error("The date to format must be non-null.");for(var c=[],d=0;d<a.b.length;++d){var e=a.b[d].text;1==a.b[d].type?c.push(Af(a,e,b,b,b)):c.push(e)}return c.join("")}
function wf(a,b){if(4>b)var c=a.a.R[b];else if(8>b)c=a.a.W[b-4];else if(12>b)c=a.a.ba[b-8],c=c.replace("{1}",a.a.R[b-8]),c=c.replace("{0}",a.a.W[b-8]);else{wf(a,10);return}b=c;for(Bf&&(b=b.replace(/\u200f/g,""));b;){c=b;for(var d=0;d<xf.length;++d){var e=b.match(xf[d]);if(e){var f=e[0];b=b.substring(f.length);0==d&&("''"==f?f="'":(f=f.substring(1,"'"==e[1]?f.length-1:f.length),f=f.replace(/''/g,"'")));a.b.push({text:f,type:d});break}}if(c===b)throw Error("Malformed pattern part: "+b);}}
function Y(a,b){b=String(b);a=a.a||of;if(void 0!==a.ta){for(var c=[],d=0;d<b.length;d++){var e=b.charCodeAt(d);c.push(48<=e&&57>=e?String.fromCharCode(a.ta+e-48):b.charAt(d))}b=c.join("")}return b}var Bf=!1;function Cf(a){if(!(a.getHours&&a.getSeconds&&a.getMinutes))throw Error("The date to format has no time (probably a goog.date.Date). Use Date or goog.date.DateTime, or use a pattern without time fields.");}
function Af(a,b,c,d,e){var f=b.length;switch(b.charAt(0)){case "G":return c=0<d.getFullYear()?1:0,4<=f?a.a.ea[c]:a.a.fa[c];case "y":return c=d.getFullYear(),0>c&&(c=-c),2==f&&(c%=100),Y(a,A(c,f));case "Y":return c=(new Date(pf(d.getFullYear(),d.getMonth(),d.getDate(),a.a.T,a.a.S))).getFullYear(),0>c&&(c=-c),2==f&&(c%=100),Y(a,A(c,f));case "M":a:switch(c=d.getMonth(),f){case 5:f=a.a.ha[c];break a;case 4:f=a.a.ga[c];break a;case 3:f=a.a.ja[c];break a;default:f=Y(a,A(c+1,f))}return f;case "k":return Cf(e),
Y(a,A(yf(e)||24,f));case "S":return Y(a,(e.getMilliseconds()/1E3).toFixed(Math.min(3,f)).substr(2)+(3<f?A(0,f-3):""));case "E":return c=d.getDay(),4<=f?a.a.sa[c]:a.a.la[c];case "a":return Cf(e),f=yf(e),a.a.aa[12<=f&&24>f?1:0];case "h":return Cf(e),Y(a,A(yf(e)%12||12,f));case "K":return Cf(e),Y(a,A(yf(e)%12,f));case "H":return Cf(e),Y(a,A(yf(e),f));case "c":a:switch(c=d.getDay(),f){case 5:f=a.a.oa[c];break a;case 4:f=a.a.ra[c];break a;case 3:f=a.a.qa[c];break a;default:f=Y(a,A(c,1))}return f;case "L":a:switch(c=
d.getMonth(),f){case 5:f=a.a.na[c];break a;case 4:f=a.a.ma[c];break a;case 3:f=a.a.pa[c];break a;default:f=Y(a,A(c+1,f))}return f;case "Q":return c=Math.floor(d.getMonth()/3),4>f?a.a.ka[c]:a.a.ia[c];case "d":return Y(a,A(d.getDate(),f));case "m":return Cf(e),Y(a,A(e.getMinutes(),f));case "s":return Cf(e),Y(a,A(e.getSeconds(),f));case "v":return f=rf(c.getTimezoneOffset()),f.f;case "V":return a=rf(c.getTimezoneOffset()),2>=f?a.f:0<uf(a,c)?void 0!==a.a.ca?a.a.ca:a.a.DST_GENERIC_LOCATION:void 0!==a.a.U?
a.a.U:a.a.STD_GENERIC_LOCATION;case "w":return c=pf(e.getFullYear(),e.getMonth(),e.getDate(),a.a.T,a.a.S),Y(a,A(Math.floor(Math.round((c-(new Date((new Date(c)).getFullYear(),0,1)).valueOf())/864E5)/7)+1,f));case "z":return a=rf(c.getTimezoneOffset()),4>f?a.g[0<uf(a,c)?2:0]:a.g[0<uf(a,c)?3:1];case "Z":return b=rf(c.getTimezoneOffset()),4>f?(f=-(b.b-uf(b,c)),a=[0>f?"-":"+"],f=Math.abs(f),a.push(A(Math.floor(f/60)%100,2),A(f%60,2)),f=a.join("")):f=Y(a,tf(b.b-uf(b,c))),f;default:return""}};function Df(a,b){b=a(b||Ef,void 0,void 0);a=Be();a=Qe(a.a,"DIV");if(Ka(b))if(b instanceof Ud){if(b.u!==Qd)throw Error("Sanitized content was not of kind HTML.");b=Bb(b.toString(),b.L||null)}else b=vb("zSoyz");else b=vb(String(b));Eb(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var Ef={};function Z(){var a=mf.call(this)||this;a.i=!1;a.b="";a.g=!1;a.f=!1;a.a=parseInt(a.getAttribute("maxresults"),10);return a}ja(Z,mf);Z.prototype.connectedCallback=function(){this.i||(this.i=!0)};
Z.prototype.attributeChangedCallback=function(a){if(["query","internal-only","all-tenants","maxresults"].includes(a)){a=this.getAttribute("query");var b=this.hasAttribute("internal-only"),c=this.hasAttribute("all-tenants"),d=parseInt(this.getAttribute("maxresults"),10);if(this.b!=a||this.g!=b||this.f!=c||this.a!=d)this.b=a,this.g=b,this.f=c,this.a=d,Ff(this)}};
function Ff(a){var b,c,d,e,f;Da(new Ca(new xa(function(h){switch(h.a){case 1:if(!a.b){Gf(a,null);h.F(0);break}var k=new ad;k=Q(k,4,a.b);k=R(k,6,a.f,!1);b=R(k,5,a.g,!1);a.a&&R(b,9,a.a,0);c=new xd("/dynamic_content");if(d=(new xd(new URL(document.location.toString()))).a.get("skip_cache"))U(c),c.a.set("skip_cache",d);h.g=3;k=jf(c.toString(),b.Ca());h.a=5;return{value:k};case 5:e=h.i;h.a=4;h.g=0;break;case 3:return h.g=0,h.b=null,h.return();case 4:if(e)try{f=new kd(e?JSON.parse(e):null)}catch(l){}f&&
Gf(a,f);h.a=0}})))}
function Hf(a,b){var c="ranking",d=!1;a.hasAttribute("sortorder")&&(c=(d=a.getAttribute("sortorder").startsWith("-"))?a.getAttribute("sortorder").substring(1):a.getAttribute("sortorder"));var e=a.getAttribute("dynamic-card-type")||"card",f="true"===a.getAttribute("show-authors"),h=parseInt(a.getAttribute("initial-results"),10)||3,k=parseInt(a.getAttribute("items-per-page"),10)||3;b=Rc(b).map(function(p,r){return If(p,r)});var l=a.hasAttribute("link-type")?a.getAttribute("link-type"):"heading",m="";
("button"===l||"both"===l)&&a.hasAttribute("button-label")&&(m=a.getAttribute("button-label"));return{va:m,X:e,C:h,D:k,Ba:l,A:b,Da:f,Z:c,$:d}}function Gf(a,b){a.c&&(Se(a.c),Se(a.h),a.c=null,a.h=null);if(b){b=Hf(a,b);var c=b.X;0===b.A.length&&(a.h=Df(te,{message:"Something went wrong. There is no dynamic content to display."}),a.appendChild(a.h));a.c="card"===c?Df(qe,b):Df(se,b);a.appendChild(a.c)}}
function If(a,b){var c=new Map,d=P(a,1,"").split("|")[0].trim(),e=S(a,ed,6);if(e){var f=P(e,1,0);var h=zf(new vf,new Date(1E3*f))}e=O(a,11).join(" ");c.set("ranking",b);c.set("displayTitle",d);c.set("type",P(a,2,""));b=P(a,4,"");b=b.includes("?")?"":b;c.set("image",b);c.set("url",P(a,7,""));c.set("summary",P(a,5,""));c.set("displayOrigin",P(a,3,""));c.set("origin",P(a,10,""));c.set("timestamp",f);c.set("formattedTimestamp",h);c.set("project",P(a,8,""));c.set("account",P(a,9,""));c.set("keywords",
e);c.forEach(function(k,l){"string"===typeof k&&c.set(l,k.trim())});return c}n.Object.defineProperties(Z,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["query","internal-only","all-tenants","maxresults"]}}});Z.prototype.attributeChangedCallback=Z.prototype.attributeChangedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-dynamic-content",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteDynamicContent",a)};}).call(this);
